package nu.miguel.persona.quest;

import net.kyori.adventure.text.minimessage.MiniMessage;
import nu.miguel.persona.Main;
import nu.miguel.persona.content.Content.*;
import nu.miguel.persona.script.EffectExecutor;
import nu.miguel.persona.state.PlayerState;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.entity.EntityType;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import java.util.*;
import nu.miguel.persona.api.PersonaApi;

public final class QuestService {
    public record Result(boolean success,String message){public static Result ok(String m){return new Result(true,m);}public static Result fail(String m){return new Result(false,m);}}
    private final Main plugin;private final MiniMessage mini=MiniMessage.miniMessage();private final ConditionEvaluator conditions;
    public QuestService(Main plugin){this.plugin=plugin;this.conditions=new ConditionEvaluator(plugin);}

    public void onLoaded(Player player){tickPlayer(player,true);}
    public Result start(Player player,String id){
        Quest q=plugin.registry().quests().get(id);if(q==null)return Result.fail("Unknown quest "+id);PlayerState s=state(player);if(s==null)return Result.fail("Your Persona data is still loading.");
        PlayerState.QuestProgress qp;
        synchronized(s){
            if(s.quests().containsKey(id))return Result.fail("That quest is already active.");
            int count=s.completions().getOrDefault(id,s.completed().contains(id)?1:0);
            if(count>0&&!q.repeatable())return Result.fail("That quest is already completed.");
            if(q.maximumCompletions()>0&&count>=q.maximumCompletions())return Result.fail("That quest has reached its completion limit.");
            long available=s.completedAt().getOrDefault(id,0L)+q.cooldown().toMillis();if(count>0&&System.currentTimeMillis()<available)return Result.fail("That quest is on cooldown for "+formatDuration(available-System.currentTimeMillis())+".");
            if(!conditions.test(q.requirements(),player,s))return Result.fail("You do not meet that quest's requirements.");
            if(q.repeatable())s.completed().remove(id);qp=new PlayerState.QuestProgress(0);s.quests().put(id,qp);
        }
        EffectExecutor.Context context=context(player,q,null,null,0,0);plugin.scripts().run(q.onStart(),context);initialize(player,q,s,qp);notify(player,plugin.getConfig().getString("messages.quest-started","<green>Quest started: <quest>").replace("<quest>",q.title()));changed(player,s);return Result.ok("Quest started.");
    }
    public Result finish(Player player,String id){PlayerState s=state(player);Quest q=plugin.registry().quests().get(id);if(q==null)return Result.fail("Unknown quest "+id);if(s==null)return Result.fail("Data is loading.");if(!s.quests().containsKey(id)&&s.completed().contains(id)&&!q.repeatable())return Result.fail("That quest is already completed.");complete(player,q,s);changed(player,s);return Result.ok("Quest completed.");}
    public Result reset(Player player,String id){PlayerState s=state(player);if(s==null)return Result.fail("Data is loading.");Quest q=plugin.registry().quests().get(id);s.quests().remove(id);s.completed().remove(id);s.completions().remove(id);s.completedAt().remove(id);if(q!=null)plugin.scripts().run(q.onReset(),context(player,q,null,null,0,0));changed(player,s);return Result.ok("Quest reset.");}

    public Result canStart(Player p,String id){PlayerState s=state(p);return s==null?Result.fail("Your Persona data is still loading."):canStart(p,s,id);}
    public Result canFinish(Player p,String id){PlayerState s=state(p);return s!=null&&s.questState(id)==QuestState.ACTIVE?Result.ok(""):Result.fail("That quest is not active.");}
    private Result canStart(Player p,PlayerState s,String id){Quest q=plugin.registry().quests().get(id);if(q==null)return Result.fail("Unknown quest.");if(s.quests().containsKey(id))return Result.fail("That quest is already active.");int n=s.completions().getOrDefault(id,s.completed().contains(id)?1:0);if(n>0&&!q.repeatable())return Result.fail("That quest cannot be started now.");if(q.maximumCompletions()>0&&n>=q.maximumCompletions())return Result.fail("That quest has reached its completion limit.");if(System.currentTimeMillis()<s.completedAt().getOrDefault(id,0L)+q.cooldown().toMillis())return Result.fail("That quest is on cooldown.");return conditions.test(q.requirements(),p,s)?Result.ok(""):Result.fail("You do not meet that quest's requirements.");}

    public Result canDeliver(Player p,String questId,String objectiveId){PlayerState s=state(p);return s==null?Result.fail("Your Persona data is still loading."):canDeliver(p,s,questId,objectiveId);}
    private Result canDeliver(Player p,PlayerState s,String questId,String objectiveId){Quest q=plugin.registry().quests().get(questId);PlayerState.QuestProgress qp=s.quests().get(questId);if(q==null||qp==null)return Result.fail("That quest is not active.");Objective o=q.phases().get(qp.phase()).objectives().stream().filter(x->x.id().equals(objectiveId)&&x.type()==ObjectiveType.DELIVER_ITEM).findFirst().orElse(null);if(o==null)return Result.fail("That delivery is not part of the current phase.");int count=count(p,o.material());if(count<o.amount())return Result.fail("You need "+o.amount()+" "+o.material().translationKey()+" (you have "+count+").");return Result.ok("");}
    public Result deliver(Player p,String questId,String objectiveId){PlayerState s=state(p);if(s==null)return Result.fail("Your Persona data is still loading.");Result valid=canDeliver(p,s,questId,objectiveId);if(!valid.success())return valid;Quest q=plugin.registry().quests().get(questId);var qp=s.quests().get(questId);Objective o=q.phases().get(qp.phase()).objectives().stream().filter(x->x.id().equals(objectiveId)).findFirst().orElseThrow();remove(p,o.material(),o.amount());progress(p,questId,objectiveId,o.amount(),true);return Result.ok("Items delivered.");}

    public void collect(Player p){PlayerState s=state(p);if(s==null)return;for(var e:new ArrayList<>(s.quests().entrySet())){Quest q=plugin.registry().quests().get(e.getKey());if(q==null||e.getValue().phase()>=q.phases().size())continue;for(Objective o:q.phases().get(e.getValue().phase()).objectives())if(o.type()==ObjectiveType.COLLECT_ITEM)progress(p,q.id(),o.id(),count(p,o.material()),false);}}
    public void kill(Player p,EntityType type){event(p,ObjectiveType.KILL_ENTITY,o->o.entity()==type,1);}public void talk(Player p,String npc,String instance){event(p,ObjectiveType.TALK_TO_NPC,o->o.npc().equals(npc)&&(o.instance()==null||o.instance().equals(instance)),1);}public void interact(Player p,Location l,Material material){event(p,ObjectiveType.INTERACT_BLOCK,o->o.position().contains(l,0.1)&&(o.material()==null||o.material()==material),1);}public void move(Player p,Location l){event(p,ObjectiveType.GO_TO_LOCATION,o->o.position().contains(l,o.radius()),1);}
    public void death(Player p){PlayerState s=state(p);if(s==null)return;long now=System.currentTimeMillis();for(var e:s.quests().entrySet()){Quest q=plugin.registry().quests().get(e.getKey());if(q==null)continue;for(Objective o:q.phases().get(e.getValue().phase()).objectives())if(o.type()==ObjectiveType.SURVIVE)ObjectiveTimers.resetSurvival(e.getValue().objectives().get(o.id()),now);}changed(p,s);}
    public void tickPlayer(Player p,boolean login){PlayerState s=state(p);if(s==null)return;collect(p);long now=System.currentTimeMillis();for(var e:new ArrayList<>(s.quests().entrySet())){Quest q=plugin.registry().quests().get(e.getKey());if(q==null)continue;if(q.timeLimit()!=null&&now-e.getValue().startedAt()>=q.timeLimit().toMillis()){fail(p,q,s,"time limit expired");continue;}for(Objective o:q.phases().get(e.getValue().phase()).objectives()){var op=e.getValue().objectives().get(o.id());if(op==null)continue;if(o.type()==ObjectiveType.WAIT)progress(p,q.id(),o.id(),ObjectiveTimers.waitElapsed(op.startedAt(),now),false);else if(o.type()==ObjectiveType.SURVIVE){if(login)op.onlineSince(now);progress(p,q.id(),o.id(),ObjectiveTimers.survivalElapsed(op.value(),op.onlineSince(),now),false);op.onlineSince(now);}}}}

    private interface Match{boolean matches(Objective o);}private void event(Player p,ObjectiveType type,Match match,long amount){PlayerState s=state(p);if(s==null)return;for(var e:new ArrayList<>(s.quests().entrySet())){Quest q=plugin.registry().quests().get(e.getKey());if(q==null)continue;for(Objective o:q.phases().get(e.getValue().phase()).objectives())if(o.type()==type&&match.matches(o))progress(p,q.id(),o.id(),amount,true);}}
    private boolean progress(Player p,String questId,String objectiveId,long value,boolean increment){PlayerState s=state(p);Quest q=plugin.registry().quests().get(questId);var qp=s==null?null:s.quests().get(questId);if(q==null||qp==null)return false;int phaseIndex=qp.phase();Phase phase=q.phases().get(phaseIndex);Objective o=phase.objectives().stream().filter(x->x.id().equals(objectiveId)).findFirst().orElse(null);if(o==null)return false;var op=qp.objectives().get(objectiveId);if(op==null)return false;long required=required(o),old=op.value();op.value(ProgressRules.update(old,value,required,increment));long current=op.value();if(current!=old){EffectExecutor.Context ctx=context(p,q,phase,o,current,required);long every=o.onProgress().every();if(every>0&&(old/every!=current/every||current==required))plugin.scripts().run(o.onProgress().script(),ctx);if(old<required&&current>=required)plugin.scripts().run(o.onComplete(),ctx);if(current==required||old==0)notify(p,msg("quest-progress").replace("<objective>",o.title()).replace("<current>",String.valueOf(current)).replace("<required>",String.valueOf(required)));plugin.behaviors().playerStateChanged(p,"objective-progress-changed",Map.of("quest",questId,"objective",objectiveId,"old",old,"new",current,"required",required));advance(p,q,s,qp,phaseIndex);changed(p,s);}return true;}
    private void advance(Player p,Quest q,PlayerState s,PlayerState.QuestProgress qp,int expectedPhase){if(qp.phase()!=expectedPhase)return;Phase phase=q.phases().get(expectedPhase);boolean hasRequired=phase.objectives().stream().anyMatch(o->!o.optional());if(!phase.objectives().stream().filter(o->!hasRequired||!o.optional()).allMatch(o->qp.objectives().get(o.id()).value()>=required(o)))return;plugin.scripts().run(phase.onComplete(),context(p,q,phase,null,0,0));notify(p,msg("phase-complete").replace("<phase>",phase.title()));String next=null;for(PhaseBranch branch:phase.branches())if(conditions.test(branch.condition(),p,s)){next=branch.nextPhase();break;}if(next!=null&&next.equalsIgnoreCase("end")){complete(p,q,s);return;}int nextIndex=next==null?expectedPhase+1:indexOf(q,next);if(nextIndex>=0&&nextIndex<q.phases().size()){qp.phase(nextIndex);initialize(p,q,s,qp);}else complete(p,q,s);}
    private void initialize(Player p,Quest q,PlayerState s,PlayerState.QuestProgress qp){long now=System.currentTimeMillis();Phase phase=q.phases().get(qp.phase());for(Objective o:phase.objectives())qp.objectives().put(o.id(),new PlayerState.ObjectiveProgress(0,now,now));EffectExecutor.Context base=context(p,q,phase,null,0,0);plugin.scripts().run(phase.onStart(),base);for(Objective o:phase.objectives())plugin.scripts().run(o.onStart(),context(p,q,phase,o,0,required(o)));}
    private void complete(Player p,Quest q,PlayerState s){s.quests().remove(q.id());s.completed().add(q.id());s.completions().merge(q.id(),1,Integer::sum);s.completedAt().put(q.id(),System.currentTimeMillis());plugin.scripts().run(q.onComplete(),context(p,q,null,null,0,0));notify(p,msg("quest-complete").replace("<quest>",q.title()));}
    private void fail(Player p,Quest q,PlayerState s,String reason){s.quests().remove(q.id());plugin.scripts().run(q.onFail(),context(p,q,null,null,0,0));notify(p,"<red>Quest failed: "+q.title()+" ("+reason+")");changed(p,s);}
    private int indexOf(Quest q,String id){for(int i=0;i<q.phases().size();i++)if(q.phases().get(i).id().equals(id))return i;return -1;}private long required(Objective o){return switch(o.type()){case WAIT,SURVIVE->o.duration().toMillis();case CUSTOM->o.requiredProgress();default->o.amount();};}
    public boolean updateProgress(Player p,String quest,String objective,long value,boolean increment){if(!plugin.getServer().isPrimaryThread())throw new IllegalStateException("progress updates must run on the server thread");return progress(p,quest,objective,value,increment);}
    public List<PersonaApi.ActiveObjective> activeObjectives(Player p,String requestedType){PlayerState s=state(p);if(s==null)return List.of();String type=requestedType==null?null:PersonaApi.canonical(requestedType);List<PersonaApi.ActiveObjective> out=new ArrayList<>();for(var e:s.quests().entrySet()){Quest q=plugin.registry().quests().get(e.getKey());if(q==null||e.getValue().phase()>=q.phases().size())continue;Phase phase=q.phases().get(e.getValue().phase());for(Objective o:phase.objectives()){String actual=o.type()==ObjectiveType.CUSTOM?o.extensionType():PersonaApi.canonical(o.type().name());if(type!=null&&!type.equals(actual))continue;var op=e.getValue().objectives().get(o.id());if(op!=null)out.add(new PersonaApi.ActiveObjective(q.id(),phase.id(),o.id(),actual,op.value(),required(o),o.options()));}}return List.copyOf(out);}
    private int count(Player p,Material m){return p.getInventory().all(m).values().stream().mapToInt(ItemStack::getAmount).sum();}private void remove(Player p,Material m,int amount){for(ItemStack item:p.getInventory().getStorageContents()){if(item==null||item.getType()!=m)continue;int take=Math.min(amount,item.getAmount());item.setAmount(item.getAmount()-take);amount-=take;if(amount==0)return;}}
    private PlayerState state(Player p){return plugin.states().require(p);}private void changed(Player p,PlayerState s){plugin.states().save(s);plugin.behaviors().playerStateChanged(p,"quest-state-changed",Map.of());}private void notify(Player p,String value){p.sendMessage(mini.deserialize(value));}private String msg(String key){return plugin.getConfig().getString("messages."+key,"<yellow>"+key);}private EffectExecutor.Context context(Player p,Quest q,Phase phase,Objective objective,long current,long required){return new EffectExecutor.Context(p,null,null,q,phase,objective,current,required);}private String formatDuration(long millis){long seconds=Math.max(1,millis/1000);return seconds>=60?(seconds/60)+"m "+(seconds%60)+"s":seconds+"s";}
}
