package nu.miguel.persona.dialogue;

import net.citizensnpcs.api.npc.NPC;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.event.ClickEvent;
import net.kyori.adventure.text.event.HoverEvent;
import net.kyori.adventure.text.minimessage.MiniMessage;
import nu.miguel.persona.Main;
import nu.miguel.persona.citizens.PersonaTrait;
import nu.miguel.persona.content.Content.*;
import nu.miguel.persona.quest.ConditionEvaluator;
import nu.miguel.persona.script.EffectExecutor;
import nu.miguel.persona.script.ScriptEngine;
import org.bukkit.entity.Player;
import org.bukkit.scheduler.BukkitTask;

import java.util.*;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;
import java.util.concurrent.ThreadLocalRandom;

/** Dialogue host for the Persona 2.0 ordered script interpreter. */
public final class DialogueService {
    public record LiveSummary(UUID playerId,String dialogueId,String nodeId,String state,String npcDefinition,String npcInstance,String currentLine,List<String> eligibleChoices,Long waitDeadline,String cancellationReason){}
    private record Cancelled(LiveSummary summary,long expiresAt) {}
    private static final int MAX_AUTOMATIC_TRANSITIONS=64;
    private final Main plugin;private final MiniMessage mini=MiniMessage.miniMessage();private final ConditionEvaluator conditions;
    private final Map<UUID,Session> sessions=new HashMap<>();private final Map<UUID,Cancelled> cancelled=new HashMap<>();private final DialogueTokenBook tokens=new DialogueTokenBook();
    private final long timeoutMillis;private final double maxDistanceSquared;private final BukkitTask monitor;
    public DialogueService(Main plugin){this.plugin=plugin;conditions=new ConditionEvaluator(plugin);timeoutMillis=nu.miguel.persona.content.Durations.parse(plugin.getConfig().getString("dialogue.inactivity-timeout","120s")).toMillis();double d=plugin.getConfig().getDouble("dialogue.maximum-distance",8);maxDistanceSquared=d*d;monitor=plugin.getServer().getScheduler().runTaskTimer(plugin,this::monitor,20,20);}

    public void begin(Player player,NPC citizensNpc){if(!plugin.states().ready(player)){player.sendMessage(mini.deserialize(plugin.getConfig().getString("messages.content-loading","<yellow>Data is loading.")));return;}PersonaTrait trait=citizensNpc.getOrAddTrait(PersonaTrait.class);if(!trait.bound())return;Npc npc=plugin.registry().npcs().get(trait.definitionId());if(npc==null){player.sendMessage(Component.text("This NPC's Persona definition is unavailable."));return;}EffectExecutor.Context context=new EffectExecutor.Context(player,citizensNpc,npc,null,null,null,0,0);plugin.scripts().run(npc.onInteract(),context).thenAccept(control->onServer(()->{if(control.kind()!=ScriptEngine.Kind.CONTINUE)return;DialogueRegistration selected=npc.dialogues().stream().filter(r->conditions.test(r.condition(),player,plugin.states().require(player))).findFirst().orElse(null);if(selected==null){plugin.scripts().run(npc.onNoDialogue(),context);return;}cancel(player.getUniqueId(),null);cancelled.remove(player.getUniqueId());Dialogue d=plugin.registry().dialogues().get(selected.dialogueId());Session session=new Session(UUID.randomUUID(),player,citizensNpc,npc,d,d.start());sessions.put(player.getUniqueId(),session);plugin.behaviors().projections().markDialogue(player,citizensNpc,true);plugin.quests().talk(player,npc.id(),trait.instanceId());runNode(session);}));}
    private void runNode(Session s){if(!current(s))return;if(++s.transitions>MAX_AUTOMATIC_TRANSITIONS){plugin.getLogger().warning("Dialogue transition limit exceeded for "+s.dialogue.id()+" player "+s.player.getUniqueId());cancel(s.player.getUniqueId(),"Conversation ended because its script looped.");return;}clearTokens(s);Node node=s.dialogue.nodes().get(s.node);if(node==null){cancel(s.player.getUniqueId(),"Conversation content changed.");return;}plugin.scripts().run(node.script(),context(s),new Host(s)).whenComplete((control,error)->onServer(()->{if(!current(s))return;if(error!=null){plugin.getLogger().warning("Dialogue script failed: "+error.getMessage());cancel(s.player.getUniqueId(),"Conversation ended unexpectedly.");return;}apply(s,control);}));}
    private void apply(Session s,ScriptEngine.Control c){switch(c.kind()){case JUMP->{s.node=c.node();runNode(s);}case TRANSFER->{Dialogue d=plugin.registry().dialogues().get(c.dialogue());if(d==null){cancel(s.player.getUniqueId(),"Conversation target is unavailable.");return;}s.dialogue=d;s.node=c.node()==null?d.start():c.node();runNode(s);}default->cancel(s.player.getUniqueId(),null);}}

    public void choose(Player player,String raw){Session s=sessions.get(player.getUniqueId());OptionalInt selected=s==null?OptionalInt.empty():tokens.consume(raw,key(s));if(selected.isEmpty()||s.choice==null){player.sendMessage(Component.text("That response is stale or invalid."));return;}CompletableFuture<Integer> future=s.choice;s.choice=null;s.eligibleChoices=List.of();clearTokens(s);s.touch();future.complete(selected.getAsInt());}
    public boolean cancel(UUID player,String reason){Session s=sessions.remove(player);if(s==null)return false;plugin.behaviors().projections().markDialogue(s.player,s.citizensNpc,false);clearTokens(s);if(s.choice!=null)s.choice.complete(-1);if(reason!=null&&s.player.isOnline())s.player.sendMessage(Component.text(reason));if(reason!=null){String instance=Objects.toString(s.citizensNpc.getTrait(PersonaTrait.class).instanceId(),s.citizensNpc.getUniqueId().toString());cancelled.put(player,new Cancelled(new LiveSummary(player,s.dialogue.id(),s.node,"cancelled",s.npc.id(),instance,s.currentLine,s.eligibleChoices,s.waitDeadline,reason),System.currentTimeMillis()+30_000));}return true;}
    public List<LiveSummary> liveSummaries(){long now=System.currentTimeMillis();cancelled.entrySet().removeIf(entry->entry.getValue().expiresAt()<now);List<LiveSummary> result=new ArrayList<>();for(Session s:sessions.values()){String state=s.choice!=null?"waiting-for-choice":s.waitDeadline!=null&&s.waitDeadline>now?"waiting":"running";result.add(new LiveSummary(s.player.getUniqueId(),s.dialogue.id(),s.node,state,s.npc.id(),Objects.toString(s.citizensNpc.getTrait(PersonaTrait.class).instanceId(),s.citizensNpc.getUniqueId().toString()),s.currentLine,s.eligibleChoices,s.waitDeadline,null));}cancelled.values().forEach(value->result.add(value.summary()));return List.copyOf(result);}
    public void cancelNpc(NPC npc){new ArrayList<>(sessions.values()).stream().filter(s->s.citizensNpc==npc).forEach(s->cancel(s.player.getUniqueId(),"Conversation ended because the NPC left."));}public void cancelAll(String reason){new ArrayList<>(sessions.keySet()).forEach(id->cancel(id,reason));}public void close(){monitor.cancel();cancelAll("Conversation cancelled.");}
    private void monitor(){long now=System.currentTimeMillis();for(Session s:new ArrayList<>(sessions.values()))if(!s.player.isOnline()||now-s.lastActivity>timeoutMillis||!s.citizensNpc.isSpawned()||s.citizensNpc.getEntity().getWorld()!=s.player.getWorld()||s.citizensNpc.getEntity().getLocation().distanceSquared(s.player.getLocation())>maxDistanceSquared)cancel(s.player.getUniqueId(),"Conversation cancelled.");}
    private final class Host implements ScriptEngine.Host {private final Session s;Host(Session s){this.s=s;}public CompletionStage<Void> say(Say say,EffectExecutor.Context context){if(!current(s))return CompletableFuture.failedFuture(new IllegalStateException("conversation ended"));String value=localized(say,s.player.locale()),rendered=plugin.effects().replace(value,context);s.currentLine=rendered;s.player.sendMessage(mini.deserialize(s.npc.displayName()).append(Component.text(": ")).append(mini.deserialize(rendered)));s.touch();CompletableFuture<Void> future=new CompletableFuture<>();long ticks=Math.max(1,(long)Math.ceil(say.delay().toMillis()/50.0));s.waitDeadline=System.currentTimeMillis()+ticks*50;plugin.getServer().getScheduler().runTaskLater(plugin,()->{if(current(s)){s.waitDeadline=null;s.currentLine=null;}future.complete(null);},ticks);return future;}public CompletionStage<Integer> choose(List<ChoiceOption> options,EffectExecutor.Context context){CompletableFuture<Integer> future=new CompletableFuture<>();s.choice=future;s.eligibleChoices=options.stream().map(option->plugin.effects().replace(option.text(),context)).toList();for(int index=0;index<options.size();index++){ChoiceOption option=options.get(index);String token=tokens.issue(key(s),index);Component line=Component.text((index+1)+". ").append(mini.deserialize(s.eligibleChoices.get(index))).hoverEvent(HoverEvent.showText(Component.text("Click to choose"))).clickEvent(ClickEvent.runCommand("/persona _choose "+token));s.player.sendMessage(line);}s.touch();return future;}public void failure(String message,Throwable error,EffectExecutor.Context context){if(error!=null)plugin.getLogger().warning("Dialogue command failed: "+error.getMessage());if(message!=null&&!message.isBlank())s.player.sendMessage(Component.text(message));}}
    private void clearTokens(Session s){tokens.clearSession(s.id);}private DialogueTokenBook.SessionKey key(Session s){return new DialogueTokenBook.SessionKey(s.id,s.player.getUniqueId(),s.citizensNpc.getUniqueId(),s.dialogue.id(),s.node);}private boolean current(Session s){return sessions.get(s.player.getUniqueId())==s;}private EffectExecutor.Context context(Session s){return new EffectExecutor.Context(s.player,s.citizensNpc,s.npc,s.dialogue,null,null,null,0,0);}private void onServer(Runnable r){if(plugin.getServer().isPrimaryThread())r.run();else plugin.getServer().getScheduler().runTask(plugin,r);}
    private static String weighted(List<WeightedText> values){int total=values.stream().mapToInt(WeightedText::weight).sum(),pick=ThreadLocalRandom.current().nextInt(total);for(WeightedText v:values){pick-=v.weight();if(pick<0)return v.text();}return values.getLast().text();}
    static String localized(Say say,Locale locale){if(say.text()!=null&&!say.text().isBlank())return say.text();if(!say.variants().isEmpty())return weighted(say.variants());String exact=locale.toLanguageTag().toLowerCase(Locale.ROOT),language=locale.getLanguage().toLowerCase(Locale.ROOT);return say.translations().getOrDefault(exact,say.translations().getOrDefault(language,say.translations().getOrDefault("default",say.textKey())));}
    private static final class Session {final UUID id;final Player player;final NPC citizensNpc;final Npc npc;Dialogue dialogue;String node,currentLine;List<String> eligibleChoices=List.of();Long waitDeadline;long lastActivity;int transitions;CompletableFuture<Integer> choice;Session(UUID id,Player player,NPC citizensNpc,Npc npc,Dialogue dialogue,String node){this.id=id;this.player=player;this.citizensNpc=citizensNpc;this.npc=npc;this.dialogue=dialogue;this.node=node;touch();}void touch(){lastActivity=System.currentTimeMillis();}}
}
