package nu.miguel.persona.content;

import nu.miguel.persona.api.*;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.Registry;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.entity.EntityType;

import java.io.File;
import java.time.Duration;
import java.util.*;
import java.util.function.Function;

import static nu.miguel.persona.content.Content.*;

/** Strict Persona 2.0 loader. Legacy executable shapes are deliberately rejected. */
public final class ContentLoader {
    private static final String MIGRATION="; Persona 2.0 requires ordered typed scripts (see AUTHORING.md migration guide)";
    private static final Set<String> BUILTIN_COMMANDS=Set.of("start-quest","finish-quest","deliver-items","set-flag","set-variable","message","action-bar","title","play-sound","particle","give-item","take-item","give-experience","run-command","teleport","lightning-effect","potion-effect","broadcast","spawn-entity","set-block","npc-animation","npc-speak","npc-move");
    private final File root; private final Duration defaultDelay; private final Function<String,Material> materials;
    private final Function<String,EntityType> entities; private final PersonaApi api; private final List<String> errors=new ArrayList<>();
    private final Map<Object,String> sources=new IdentityHashMap<>(); private String source;

    public ContentLoader(File root,Duration defaultDelay){this(root,defaultDelay,ContentLoader::bukkitMaterial,ContentLoader::bukkitEntity,null);}
    public ContentLoader(File root,Duration defaultDelay,PersonaApi api){this(root,defaultDelay,ContentLoader::bukkitMaterial,ContentLoader::bukkitEntity,api);}
    ContentLoader(File root,Duration delay,Function<String,Material> materials,Function<String,EntityType> entities){this(root,delay,materials,entities,null);}
    ContentLoader(File root,Duration delay,Function<String,Material> materials,Function<String,EntityType> entities,PersonaApi api){this.root=root;defaultDelay=delay;this.materials=materials;this.entities=entities;this.api=api;}

    public Content.Registry load() throws ContentException {
        errors.clear();sources.clear();
        if(new File(root,"effects.yml").isFile())errors.add("effects.yml: obsolete effects.yml"+MIGRATION);
        Map<String,List<Step>> scripts=loadScripts();
        Map<String,Npc> npcs=loadDirectory("npcs",this::npc);Map<String,Dialogue> dialogues=loadDirectory("dialogues",this::dialogue);Map<String,Quest> quests=loadDirectory("quests",this::quest);
        validate(npcs,dialogues,quests,scripts);if(!errors.isEmpty())throw new ContentException(errors);
        return new Content.Registry(Map.copyOf(npcs),Map.copyOf(dialogues),Map.copyOf(quests),Map.copyOf(scripts));
    }

    private Map<String,List<Step>> loadScripts(){File file=new File(root,"scripts.yml");if(!file.isFile())return Map.of();source="scripts.yml";YamlConfiguration y=YamlConfiguration.loadConfiguration(file);ConfigurationSection s=y.getConfigurationSection("scripts");if(s==null){errors.add(source+": missing scripts section");return Map.of();}Map<String,List<Step>> out=new LinkedHashMap<>();for(String id:s.getKeys(false))try{out.put(id,steps(s.get(id),"script "+id));}catch(RuntimeException e){error(e);}return out;}
    private <T> Map<String,T> loadDirectory(String dir,Function<ConfigurationSection,T> parser){File folder=new File(root,dir);if(!folder.exists()&&!folder.mkdirs())errors.add(dir+": cannot create directory");Map<String,T> out=new LinkedHashMap<>();File[] files=folder.listFiles(f->f.isFile()&&(f.getName().endsWith(".yml")||f.getName().endsWith(".yaml")));if(files==null)return out;Arrays.sort(files,Comparator.comparing(File::getName));for(File f:files){source=dir+"/"+f.getName();try{T value=parser.apply(YamlConfiguration.loadConfiguration(f));sources.put(value,source);String id=value instanceof Npc n?n.id():value instanceof Dialogue d?d.id():((Quest)value).id();if(out.putIfAbsent(id,value)!=null)throw new IllegalArgumentException("duplicate ID "+id);}catch(RuntimeException e){error(e);}}return out;}

    private Npc npc(ConfigurationSection s){reject(s,"actions","effects","on-interact-effects");String id=id(s.getString("id"),"id");List<DialogueRegistration> ds=new ArrayList<>();for(Map<?,?> m:maps(s,"dialogues")){reject(m,"conditions");ds.add(new DialogueRegistration(id(str(m,"id"),"dialogue id"),integer(m,"priority",0),m.containsKey("when")?condition(m.get("when")):new All(List.of())));}ds.sort(Comparator.comparingInt(DialogueRegistration::priority).reversed());return new Npc(id,s.getString("display-name",id),List.copyOf(ds),steps(s.get("on-interact"),"on-interact"),steps(s.get("on-no-dialogue"),"on-no-dialogue"));}
    private Dialogue dialogue(ConfigurationSection s){String id=id(s.getString("id"),"id"),start=required(s.getString("start"),"start");ConfigurationSection ns=required(s.getConfigurationSection("nodes"),"nodes");Map<String,Node> nodes=new LinkedHashMap<>();for(String nodeId:ns.getKeys(false)){ConfigurationSection n=required(ns.getConfigurationSection(nodeId),"node "+nodeId);reject(n,"lines","choices","on-enter","on-exit");nodes.put(nodeId,new Node(nodeId,steps(n.get("script"),"node script")));}return new Dialogue(id,start,Map.copyOf(nodes));}
    private Quest quest(ConfigurationSection s){reject(s,"rewards");String id=id(s.getString("id"),"id");List<Phase> phases=new ArrayList<>();for(Map<?,?> p:maps(s,"phases")){reject(p,"rewards");List<Objective> objectives=new ArrayList<>();if(p.get("objectives") instanceof List<?> list)for(Object raw:list)objectives.add(objective(asMap(raw)));List<PhaseBranch> branches=new ArrayList<>();if(p.get("branches") instanceof List<?> list)for(Object raw:list){Map<?,?> b=asMap(raw);reject(b,"conditions");branches.add(new PhaseBranch(condition(required(b.get("when"),"branch when")),required(str(b,"next-phase"),"next-phase").toLowerCase(Locale.ROOT)));}String pid=required(str(p,"id"),"phase id").toLowerCase(Locale.ROOT);phases.add(new Phase(pid,optional(str(p,"title"),pid),optional(str(p,"description"),""),List.copyOf(objectives),steps(p.get("on-start"),"phase on-start"),steps(p.get("on-complete"),"phase on-complete"),List.copyOf(branches)));}if(phases.isEmpty())throw new IllegalArgumentException("quest needs at least one phase");boolean repeat=s.getBoolean("repeatable",false);return new Quest(id,s.getString("title",id),s.getString("description",""),List.copyOf(phases),s.contains("requirements")?legacyCondition():s.contains("when")?condition(s.get("when")):new All(List.of()),repeat,s.contains("cooldown")?Durations.parse(s.get("cooldown")):Duration.ZERO,s.getInt("maximum-completions",repeat?0:1),s.contains("time-limit")?Durations.parse(s.get("time-limit")):null,steps(s.get("on-start"),"quest on-start"),steps(s.get("on-complete"),"quest on-complete"),steps(s.get("on-fail"),"quest on-fail"),steps(s.get("on-reset"),"quest on-reset"));}
    private Condition legacyCondition(){throw new IllegalArgumentException("obsolete requirements condition map"+MIGRATION);}

    private Objective objective(Map<?,?> m){reject(m,"effects");String oid=required(str(m,"id"),"objective id"),rawType=required(str(m,"type"),"objective type");ObjectiveType type=enumOrNull(ObjectiveType.class,rawType);String extension=null;Map<String,Object> options=Map.of();long requiredProgress=integer(m,"amount",1);if(type==null){extension=custom(rawType,ExpansionTypes.Objective.class);ExpansionTypes.ObjectiveDefinition d=api.handler(ExpansionTypes.Objective.class,extension).orElseThrow().parse(stringMap(m));options=d.data();requiredProgress=d.required();type=ObjectiveType.CUSTOM;}Material material=m.containsKey("material")?material(str(m,"material")):null;EntityType entity=m.containsKey("entity")?entity(str(m,"entity")):null;int amount=integer(m,"amount",1);String npc=m.containsKey("npc")?id(str(m,"npc"),"npc"):null;Position position=null;if(m.get("location")!=null){Map<?,?> l=asMap(m.get("location"));position=new Position(required(str(l,"world"),"world"),number(l,"x"),number(l,"y"),number(l,"z"));}Duration duration=m.containsKey("duration")?Durations.parse(m.get("duration")):null;if(amount<1)throw new IllegalArgumentException("objective amount must be positive");switch(type){case COLLECT_ITEM,DELIVER_ITEM->required(material,type+" material");case KILL_ENTITY->required(entity,"kill-entity entity");case TALK_TO_NPC->required(npc,"talk-to-npc npc");case GO_TO_LOCATION,INTERACT_BLOCK->required(position,type+" location");case WAIT,SURVIVE->required(duration,type+" duration");default->{}}ProgressHook progress=progressHook(m,type==ObjectiveType.WAIT||type==ObjectiveType.SURVIVE);return new Objective(oid,optional(str(m,"title"),oid),optional(str(m,"description"),""),type,material,entity,amount,npc,str(m,"instance"),position,m.containsKey("radius")?number(m,"radius"):1.5,duration,bool(m.get("optional"),false),bool(m.get("hidden"),false),steps(m.get("on-start"),"objective on-start"),progress,steps(m.get("on-complete"),"objective on-complete"),extension,options,requiredProgress);}
    private ProgressHook progressHook(Map<?,?> m,boolean duration){Object raw=m.get("on-progress");if(raw==null)return new ProgressHook(0,List.of());if(!(raw instanceof Map<?,?> p))throw new IllegalArgumentException("on-progress must contain every and script");reject(p,"effects");Object every=p.get("every");long interval=every==null?1:every instanceof Number n?n.longValue():duration?Durations.parse(every).toMillis():Long.parseLong(String.valueOf(every));return new ProgressHook(interval,steps(p.get("script"),"on-progress script"));}

    private List<Step> steps(Object raw,String what){if(raw==null)return List.of();if(!(raw instanceof List<?> list))throw new IllegalArgumentException(what+" must be a list");List<Step> out=new ArrayList<>();for(Object value:list)out.add(step(asMap(value)));return List.copyOf(out);}
    private Step step(Map<?,?> m){reject(m,"use","actions","effects");String type=required(str(m,"type"),"script step type");if(!type.equals(type.toLowerCase(Locale.ROOT))||type.contains("_"))throw new IllegalArgumentException("step type must be lowercase kebab-case: "+type);return switch(type){
        case "say"->{List<WeightedText> variants=new ArrayList<>();Object raw=m.get("variants");if(raw instanceof List<?> list)for(Object v:list){Map<?,?> x=asMap(v);variants.add(new WeightedText(required(str(x,"text"),"variant text"),positive(integer(x,"weight",1),"weight")));}String text=str(m,"text");if((text==null||text.isBlank())&&variants.isEmpty())throw new IllegalArgumentException("say needs text or variants");yield new Say(text,List.copyOf(variants),m.containsKey("delay")?Durations.parse(m.get("delay")):defaultDelay);}
        case "if"->new If(condition(required(m.get("when"),"if when")),steps(m.get("then"),"then"),steps(m.get("else"),"else"));
        case "choice"->{if(!(m.get("options") instanceof List<?> list))throw new IllegalArgumentException("choice options must be a list");List<ChoiceOption> options=new ArrayList<>();for(Object raw:list){Map<?,?> o=asMap(raw);reject(o,"actions","effects","conditions");options.add(new ChoiceOption(required(str(o,"text"),"choice text"),o.containsKey("when")?condition(o.get("when")):new All(List.of()),steps(o.get("script"),"choice option script")));}yield new ChoiceStep(List.copyOf(options));}
        case "goto"->{String node=str(m,"node"),dialogue=str(m,"dialogue");if(node==null&&dialogue==null)throw new IllegalArgumentException("goto needs node or dialogue");yield new Goto(node,dialogue);}
        case "end-dialogue"->new EndDialogue();case "stop"->new Stop();case "wait"->new Wait(Durations.parse(required(m.get("duration"),"wait duration")));
        case "random"->{if(!(m.get("options") instanceof List<?> list))throw new IllegalArgumentException("random options must be a list");List<WeightedScript> options=new ArrayList<>();for(Object raw:list){Map<?,?> o=asMap(raw);options.add(new WeightedScript(positive(integer(o,"weight",1),"weight"),steps(o.get("script"),"random script")));}if(options.isEmpty())throw new IllegalArgumentException("random needs options");yield new RandomStep(List.copyOf(options));}
        case "run-script"->new RunScript(required(str(m,"script"),"script name"));
        default->{String key=PersonaApi.canonical(type);if(api!=null&&!api.registeredTypes(ExpansionTypes.Command.class).contains(key))throw new IllegalArgumentException("unavailable command type "+key);if(api==null&&(type.contains(":")||!BUILTIN_COMMANDS.contains(type)))throw new IllegalArgumentException("unavailable command type "+key);Map<String,Object> data=stringMap(m);data.keySet().removeAll(Set.of("type","on-success","on-failure"));if(api!=null&&type.contains(":"))data=new LinkedHashMap<>(api.handler(ExpansionTypes.Command.class,key).orElseThrow().parse(Map.copyOf(data)));validateBuiltinYaml(type,data);yield new Command(key,Map.copyOf(data),steps(m.get("on-success"),"on-success"),steps(m.get("on-failure"),"on-failure"));}
    };}
    private void validateBuiltinYaml(String type,Map<String,Object> data){switch(type){case "start-quest","finish-quest"->required(data.get("quest"),type+" quest");case "deliver-items"->{required(data.get("quest"),"deliver-items quest");required(data.get("objective"),"deliver-items objective");}case "give-item","take-item","set-block"->{material(String.valueOf(required(data.get("material"),type+" material")));if((type.equals("give-item")||type.equals("take-item"))&&integer(data,"amount",1)<1)throw new IllegalArgumentException(type+" amount must be positive");}case "give-experience"->{if(integer(data,"amount",1)<1)throw new IllegalArgumentException("give-experience amount must be positive");}case "set-flag"->required(data.get("flag"),"set-flag flag");case "set-variable"->required(data.containsKey("variable")?data.get("variable"):data.get("name"),"set-variable variable");case "spawn-entity"->entity(String.valueOf(required(data.get("entity"),"spawn-entity entity")));default->{}}}

    private Condition condition(Object raw){if(raw instanceof List<?> list)return new All(list.stream().map(this::condition).toList());Map<?,?> m=asMap(raw);String type=required(str(m,"type"),"condition type");if(!type.equals(type.toLowerCase(Locale.ROOT))||type.contains("_"))throw new IllegalArgumentException("condition type must be lowercase kebab-case: "+type);return switch(type){case "all"->new All(conditionChildren(m));case "any"->new Any(conditionChildren(m));case "not"->new Not(condition(required(m.get("when"),"not when")));case "quest-state"->new QuestStateCondition(id(str(m,"quest"),"quest"),enumValue(QuestState.class,str(m,"state"),"quest state"));case "item-count"->new ItemCount(material(str(m,"material")),positive(integer(m,"amount",1),"amount"));case "flag"->new Flag(required(str(m,"name"),"flag name"),bool(m.get("value"),true));case "variable"->new VariableCondition(required(str(m,"name"),"variable name"),enumValue(Comparison.class,optional(str(m,"operator"),"equals"),"variable operator"),optional(str(m,"value"),""));case "permission"->new PermissionCondition(required(str(m,"permission"),"permission"));case "world"->new WorldCondition(required(str(m,"world"),"world"));case "chance"->{double chance=number(m,"chance");if(chance<0||chance>1)throw new IllegalArgumentException("chance must be between 0 and 1");yield new ChanceCondition(chance);}default->{String key=custom(type,ExpansionTypes.Condition.class);Map<String,Object> data=stringMap(m);data.remove("type");yield new CustomCondition(key,api.handler(ExpansionTypes.Condition.class,key).orElseThrow().parse(Map.copyOf(data)));}};}
    private List<Condition> conditionChildren(Map<?,?> m){Object raw=m.get("conditions");if(!(raw instanceof List<?> list))throw new IllegalArgumentException("composite condition needs conditions list");return list.stream().map(this::condition).toList();}

    private void validate(Map<String,Npc> npcs,Map<String,Dialogue> dialogues,Map<String,Quest> quests,Map<String,List<Step>> scripts){for(Npc n:npcs.values()){source=sources.get(n);for(DialogueRegistration r:n.dialogues()){if(!dialogues.containsKey(r.dialogueId()))error(n.id()+" references missing dialogue "+r.dialogueId());validateCondition(r.condition(),quests);}validateSteps(n.onInteract(),null,dialogues,quests,scripts,false);validateSteps(n.onNoDialogue(),null,dialogues,quests,scripts,false);}for(Dialogue d:dialogues.values()){source=sources.get(d);if(!d.nodes().containsKey(d.start()))error(d.id()+" has missing start node "+d.start());for(Node n:d.nodes().values())validateSteps(n.script(),d,dialogues,quests,scripts,true);}for(Quest q:quests.values()){source=sources.get(q);validateCondition(q.requirements(),quests);Set<String> phaseIds=new HashSet<>();for(Phase p:q.phases())if(!phaseIds.add(p.id()))error(q.id()+" has duplicate phase "+p.id());for(Phase p:q.phases()){if(p.objectives().isEmpty())error(q.id()+" phase "+p.id()+" has no objectives");Set<String> ids=new HashSet<>();for(Objective o:p.objectives()){if(!ids.add(o.id()))error(q.id()+" phase "+p.id()+" has duplicate objective "+o.id());if(o.npc()!=null&&!npcs.containsKey(o.npc()))error(q.id()+" references missing NPC "+o.npc());validateSteps(o.onStart(),null,dialogues,quests,scripts,false);validateSteps(o.onProgress().script(),null,dialogues,quests,scripts,false);validateSteps(o.onComplete(),null,dialogues,quests,scripts,false);}for(PhaseBranch b:p.branches()){validateCondition(b.condition(),quests);if(!b.nextPhase().equals("end")&&!phaseIds.contains(b.nextPhase()))error(q.id()+" branch references missing phase "+b.nextPhase());}validateSteps(p.onStart(),null,dialogues,quests,scripts,false);validateSteps(p.onComplete(),null,dialogues,quests,scripts,false);}validateSteps(q.onStart(),null,dialogues,quests,scripts,false);validateSteps(q.onComplete(),null,dialogues,quests,scripts,false);validateSteps(q.onFail(),null,dialogues,quests,scripts,false);validateSteps(q.onReset(),null,dialogues,quests,scripts,false);}detectRecursion(scripts);}
    private void validateSteps(List<Step> values,Dialogue owner,Map<String,Dialogue> dialogues,Map<String,Quest> quests,Map<String,List<Step>> scripts,boolean dialogue){validateSteps(values,owner,dialogues,quests,scripts,dialogue,new HashSet<>());}
    private void validateSteps(List<Step> values,Dialogue owner,Map<String,Dialogue> dialogues,Map<String,Quest> quests,Map<String,List<Step>> scripts,boolean dialogue,Set<String> reusableStack){for(Step s:values){if(s instanceof If x){validateCondition(x.when(),quests);validateSteps(x.thenScript(),owner,dialogues,quests,scripts,dialogue,reusableStack);validateSteps(x.elseScript(),owner,dialogues,quests,scripts,dialogue,reusableStack);}else if(s instanceof ChoiceStep x){if(!dialogue)error("choice is only valid in dialogue scripts");for(ChoiceOption o:x.options()){validateCondition(o.when(),quests);validateSteps(o.script(),owner,dialogues,quests,scripts,dialogue,reusableStack);}}else if(s instanceof Goto g){if(!dialogue)error("goto is only valid in dialogue scripts");Dialogue target=g.dialogue()==null?owner:dialogues.get(g.dialogue());if(g.dialogue()!=null&&target==null)error("goto references missing dialogue "+g.dialogue());if(target!=null&&g.node()!=null&&!target.nodes().containsKey(g.node()))error("goto references missing node "+g.node());}else if(s instanceof EndDialogue&&!dialogue)error("end-dialogue is only valid in dialogue scripts");else if(s instanceof RunScript r){if(!scripts.containsKey(r.script()))error("run-script references missing script "+r.script());else if(reusableStack.add(r.script())){validateSteps(scripts.get(r.script()),owner,dialogues,quests,scripts,dialogue,reusableStack);reusableStack.remove(r.script());}}else if(s instanceof RandomStep r)r.options().forEach(o->validateSteps(o.script(),owner,dialogues,quests,scripts,dialogue,reusableStack));else if(s instanceof Command c){validateCommand(c,quests);validateSteps(c.onSuccess(),owner,dialogues,quests,scripts,dialogue,reusableStack);validateSteps(c.onFailure(),owner,dialogues,quests,scripts,dialogue,reusableStack);}}}
    private void validateCommand(Command c,Map<String,Quest> quests){String type=c.type();if(type.equals("persona:start-quest")||type.equals("persona:finish-quest")){String q=String.valueOf(c.options().get("quest"));if(!quests.containsKey(q))error(type+" references missing quest "+q);}if(type.equals("persona:deliver-items")){String q=String.valueOf(c.options().get("quest")),o=String.valueOf(c.options().get("objective"));Quest quest=quests.get(q);if(quest==null)error(type+" references missing quest "+q);else if(quest.phases().stream().flatMap(p->p.objectives().stream()).noneMatch(x->x.id().equals(o)&&x.type()==ObjectiveType.DELIVER_ITEM))error("deliver-items references missing delivery objective "+q+"/"+o);}}
    private void validateCondition(Condition c,Map<String,Quest> quests){if(c instanceof All a)a.conditions().forEach(x->validateCondition(x,quests));else if(c instanceof Any a)a.conditions().forEach(x->validateCondition(x,quests));else if(c instanceof Not n)validateCondition(n.condition(),quests);else if(c instanceof QuestStateCondition q&&!quests.containsKey(q.quest()))error("condition references missing quest "+q.quest());}
    private void detectRecursion(Map<String,List<Step>> scripts){for(String root:scripts.keySet())visit(root,scripts,new LinkedHashSet<>());}private void visit(String name,Map<String,List<Step>> scripts,LinkedHashSet<String> path){if(!path.add(name)){error("recursive reusable script: "+String.join(" -> ",path)+" -> "+name);return;}for(String child:references(scripts.getOrDefault(name,List.of())))visit(child,scripts,new LinkedHashSet<>(path));}private List<String> references(List<Step> steps){List<String> out=new ArrayList<>();for(Step s:steps){if(s instanceof RunScript r)out.add(r.script());else if(s instanceof If i){out.addAll(references(i.thenScript()));out.addAll(references(i.elseScript()));}else if(s instanceof ChoiceStep c)c.options().forEach(o->out.addAll(references(o.script())));else if(s instanceof RandomStep r)r.options().forEach(o->out.addAll(references(o.script())));else if(s instanceof Command c){out.addAll(references(c.onSuccess()));out.addAll(references(c.onFailure()));}}return out;}

    private String custom(String raw,Class<?> category){if(api==null||!raw.contains(":"))throw new IllegalArgumentException("unknown "+category.getSimpleName().toLowerCase(Locale.ROOT)+" type "+raw);String key=PersonaApi.canonical(raw);if(!api.registeredTypes(category).contains(key))throw new IllegalArgumentException("unavailable namespaced type "+key);return key;}
    private Material material(String raw){Material m=materials.apply(required(raw,"material"));if(m==null)throw new IllegalArgumentException("invalid material "+raw);return m;}private EntityType entity(String raw){EntityType e=entities.apply(required(raw,"entity"));if(e==null)throw new IllegalArgumentException("invalid entity type "+raw);return e;}private static Material bukkitMaterial(String raw){Material m=Material.matchMaterial(raw);return m!=null&&(m.isItem()||m.isBlock())?m:null;}private static EntityType bukkitEntity(String raw){NamespacedKey k=NamespacedKey.fromString(raw);return k==null?null:Registry.ENTITY_TYPE.get(k);}
    private String id(String value,String what){return Ids.require(value,source+" "+what);}private void error(RuntimeException e){errors.add(source+": "+(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage()));}private void error(String e){errors.add(source+": "+e);}
    private static void reject(ConfigurationSection s,String...keys){for(String k:keys)if(s.contains(k))throw new IllegalArgumentException("obsolete key '"+k+"'"+MIGRATION);}private static void reject(Map<?,?> m,String...keys){for(String k:keys)if(m.containsKey(k))throw new IllegalArgumentException("obsolete key '"+k+"'"+MIGRATION);}
    private static List<Map<?,?>> maps(ConfigurationSection s,String path){return new ArrayList<>(s.getMapList(path));}private static Map<?,?> asMap(Object raw){if(raw instanceof Map<?,?> m)return m;if(raw instanceof ConfigurationSection s)return s.getValues(false);throw new IllegalArgumentException("expected map, got "+raw);}private static Map<String,Object> stringMap(Map<?,?> m){Map<String,Object> out=new LinkedHashMap<>();m.forEach((k,v)->out.put(String.valueOf(k),v));return out;}
    private static String str(Map<?,?> m,String k){Object v=m.get(k);return v==null?null:String.valueOf(v);}private static String optional(String v,String fallback){return v==null?fallback:v;}private static int integer(Map<?,?> m,String k,int fallback){Object v=m.get(k);return v instanceof Number n?n.intValue():v==null?fallback:Integer.parseInt(String.valueOf(v));}private static int positive(int n,String what){if(n<1)throw new IllegalArgumentException(what+" must be positive");return n;}private static double number(Map<?,?> m,String k){Object v=m.get(k);return v instanceof Number n?n.doubleValue():Double.parseDouble(String.valueOf(required(v,k)));}private static boolean bool(Object v,boolean fallback){return v==null?fallback:v instanceof Boolean b?b:Boolean.parseBoolean(String.valueOf(v));}
    private static <E extends Enum<E>>E enumValue(Class<E> t,String v,String what){String value=required(v,what);if(!value.equals(value.toLowerCase(Locale.ROOT))||value.contains("_"))throw new IllegalArgumentException(what+" must be lowercase kebab-case: "+value);try{return Enum.valueOf(t,value.toUpperCase(Locale.ROOT).replace('-','_'));}catch(IllegalArgumentException e){throw new IllegalArgumentException("invalid "+what+" "+value);}}private static <E extends Enum<E>>E enumOrNull(Class<E> t,String v){if(!v.equals(v.toLowerCase(Locale.ROOT))||v.contains("_"))throw new IllegalArgumentException(t.getSimpleName()+" value must be lowercase kebab-case: "+v);try{return Enum.valueOf(t,v.toUpperCase(Locale.ROOT).replace('-','_'));}catch(IllegalArgumentException e){return null;}}private static <T>T required(T v,String what){if(v==null||v instanceof String s&&s.isBlank())throw new IllegalArgumentException("missing "+what);return v;}
}
