package nu.miguel.persona.behavior;

import nu.miguel.persona.behavior.BehaviorDefinition.BehaviorNode;
import org.junit.jupiter.api.Test;

import java.util.*;
import java.util.concurrent.CompletableFuture;

import static org.junit.jupiter.api.Assertions.*;

class BehaviorRuntimeTest {
    @Test void memorySequenceResumesItsRunningChild(){BehaviorNode first=node("first","condition",Map.of()),action=node("async","action",Map.of()),last=node("last","condition",Map.of()),root=composite("root","sequence",first,action,last);CompletableFuture<BehaviorStatus> future=new CompletableFuture<>();Env env=new Env(future);BehaviorRuntime runtime=runtime(root,env);assertEquals(BehaviorStatus.RUNNING,tick(runtime));assertEquals(List.of("first"),env.conditions);assertEquals(BehaviorStatus.RUNNING,tick(runtime));assertEquals(List.of("first"),env.conditions);future.complete(BehaviorStatus.SUCCESS);assertEquals(BehaviorStatus.SUCCESS,tick(runtime));assertEquals(List.of("first","last"),env.conditions);}
    @Test void reactivePriorityInterruptsLowerBranch(){BehaviorNode highCondition=node("high-condition","condition",Map.of()),highAction=node("high-action","action",Map.of()),high=composite("high","sequence",highCondition,highAction),low=node("low","action",Map.of()),root=composite("root","priority-selector",high,low);CompletableFuture<BehaviorStatus> pending=new CompletableFuture<>();Env env=new Env(pending);env.condition=false;BehaviorRuntime runtime=runtime(root,env);assertEquals(BehaviorStatus.RUNNING,tick(runtime));env.condition=true;env.next=CompletableFuture.completedFuture(BehaviorStatus.SUCCESS);assertEquals(BehaviorStatus.SUCCESS,tick(runtime));assertTrue(env.cancelled.contains("low"));}
    @Test void parallelDoesNotRepeatCompletedChildren(){BehaviorNode done=node("done","action",Map.of()),pending=node("pending","action",Map.of()),root=new BehaviorNode("root","parallel",List.of(done,pending),null,null,Map.of("success-threshold",2,"failure-threshold",1));Env env=new Env(CompletableFuture.completedFuture(BehaviorStatus.SUCCESS));env.byId.put("pending",new CompletableFuture<>());BehaviorRuntime runtime=runtime(root,env);assertEquals(BehaviorStatus.RUNNING,tick(runtime));assertEquals(1,env.calls.get("done"));assertEquals(BehaviorStatus.RUNNING,tick(runtime));assertEquals(1,env.calls.get("done"));env.byId.get("pending").complete(BehaviorStatus.SUCCESS);assertEquals(BehaviorStatus.SUCCESS,tick(runtime));}
    @Test void checkpointSnapshotRestoresAbsoluteWait(){BehaviorNode wait=node("wait","wait",Map.of("duration","1s")),root=new BehaviorNode("save","checkpoint",List.of(),wait,null,Map.of());Env env=new Env(null);BehaviorRuntime original=runtime(root,env);assertEquals(BehaviorStatus.RUNNING,tick(original));BehaviorRuntime.Snapshot snapshot=original.snapshot();assertEquals("save",snapshot.checkpoint());env.now=1500;BehaviorRuntime restored=runtime(root,env);restored.restore(snapshot);assertEquals(BehaviorStatus.SUCCESS,tick(restored));}
    private static BehaviorRuntime runtime(BehaviorNode root,Env env){Map<String,BehaviorNode> nodes=new HashMap<>();collect(root,nodes);BehaviorDefinition d=new BehaviorDefinition("test:tree",BehaviorScope.PLAYER,root,nodes,"hash");return new BehaviorRuntime(d,env);}
    private static BehaviorStatus tick(BehaviorRuntime r){return r.tick(new BehaviorRuntime.Budget(100,1_000_000_000));}
    private static BehaviorNode node(String id,String type,Map<String,Object> options){return new BehaviorNode(id,type,List.of(),null,null,options);}private static BehaviorNode composite(String id,String type,BehaviorNode... children){return new BehaviorNode(id,type,List.of(children),null,null,Map.of());}private static void collect(BehaviorNode n,Map<String,BehaviorNode> out){out.put(n.id(),n);if(n.child()!=null)collect(n.child(),out);n.children().forEach(x->collect(x,out));}
    private static final class Env implements BehaviorRuntime.Environment {long now=100;boolean condition=true;CompletableFuture<BehaviorStatus> next;final Map<String,CompletableFuture<BehaviorStatus>> byId=new HashMap<>();final Map<String,Integer> calls=new HashMap<>();final List<String> conditions=new ArrayList<>(),cancelled=new ArrayList<>();Env(CompletableFuture<BehaviorStatus> next){this.next=next;}public long now(){return now;}public boolean condition(BehaviorNode n,BehaviorEvent e){conditions.add(n.id());return condition;}public java.util.concurrent.CompletionStage<BehaviorStatus> action(BehaviorNode n){calls.merge(n.id(),1,Integer::sum);return byId.getOrDefault(n.id(),next);}public void cancel(BehaviorNode n){cancelled.add(n.id());}}
}
