package nu.miguel.persona.behavior;

import net.citizensnpcs.api.CitizensAPI;
import net.citizensnpcs.api.npc.NPC;
import nu.miguel.persona.Main;
import nu.miguel.persona.api.BehaviorContext;
import nu.miguel.persona.api.ExpansionTypes;
import nu.miguel.persona.api.NpcMemoryService;
import nu.miguel.persona.citizens.PersonaTrait;
import nu.miguel.persona.citizens.ProjectionManager;
import nu.miguel.persona.content.Content;
import nu.miguel.persona.content.Durations;
import nu.miguel.persona.script.EffectExecutor;
import org.bukkit.Location;
import org.bukkit.entity.Player;

import java.time.Duration;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import nu.miguel.persona.state.SqliteStore;

/** Owns shared and player/NPC runtimes and bridges native actions to Bukkit/Citizens. */
public final class BehaviorService implements AutoCloseable {
    private record Key(UUID base,UUID player) {}
    private record Entry(NPC base,Player player,BehaviorDefinition definition,BehaviorRuntime runtime) {}
    private record PersistKey(String scope,String player,String npc,String instance) {}
    private final Main plugin;private final NpcMemoryService memories;private final ProjectionManager projections;private final BehaviorScheduler scheduler=new BehaviorScheduler();private final Map<Key,Entry> entries=new LinkedHashMap<>();
    private final int evaluationLimit;private final long nanosLimit;private int ticks;
    private final Set<Key> nearby=new HashSet<>();private final double proximitySquared;
    private final Map<PersistKey,SqliteStore.BehaviorRow> persisted=new HashMap<>();
    public BehaviorService(Main plugin,NpcMemoryService memories,ProjectionManager projections){this.plugin=plugin;this.memories=memories;this.projections=projections;evaluationLimit=plugin.getConfig().getInt("behavior.scheduler.node-evaluations",5000);nanosLimit=(long)(plugin.getConfig().getDouble("behavior.scheduler.milliseconds",4)*1_000_000);double proximity=plugin.getConfig().getDouble("behavior.senses.proximity-range",16);proximitySquared=proximity*proximity;for(SqliteStore.BehaviorRow row:plugin.store().loadBehaviorRuntimes().join())persisted.put(new PersistKey(row.scope(),row.player(),row.npcDefinition(),row.instance()),row);}
    public void tick(){if(ticks++%20==0)discover();if(ticks%10==0)scanProximity();scheduler.tick(evaluationLimit,nanosLimit);for(Entry e:entries.values())if(e.player!=null){String anchor=e.runtime.anchor();if(anchor==null&&e.runtime.visible())projections.inherit(e.player,e.base);else projections.apply(e.player,e.base,anchor,e.runtime.visible(),false);}projections.tick();}
    public void reload(){capture();entries.values().forEach(e->scheduler.remove(e.runtime));entries.clear();discover();flush(true);}
    public void flush(boolean synchronous){capture();CompletableFuture<Void> future=plugin.store().saveBehaviorRuntimes(new ArrayList<>(persisted.values()));if(synchronous)future.join();}
    public void wake(NPC npc,Player player,String type,Map<String,Object> data){NPC base=base(npc);BehaviorEvent event=new BehaviorEvent(type,Instant.now(),data);Entry shared=entries.get(new Key(base.getUniqueId(),null));if(shared!=null)shared.runtime.signal(event);if(player!=null){Entry own=entries.get(new Key(base.getUniqueId(),player.getUniqueId()));if(own!=null)own.runtime.signal(event);}}
    public void playerJoined(Player player){discover();for(Entry e:entries.values())if(e.player==player)e.runtime.signal(BehaviorEvent.of("player-join"));projections.playerJoined(player);}
    public void playerQuit(Player player){capture();removePlayer(player.getUniqueId());flush(true);projections.playerQuit(player.getUniqueId());}
    public Optional<BehaviorRuntime> runtime(NPC npc,Player player){return Optional.ofNullable(entries.get(new Key(base(npc).getUniqueId(),player==null?null:player.getUniqueId()))).map(Entry::runtime);}
    public ProjectionManager projections(){return projections;}
    private void discover(){Set<Key> seen=new HashSet<>();for(NPC npc:CitizensAPI.getNPCRegistry()){PersonaTrait trait=npc.getTraitNullable(PersonaTrait.class);if(trait==null||!trait.bound()||trait.projection())continue;Content.Npc definition=plugin.registry().npcs().get(trait.definitionId());if(definition==null)continue;if(definition.sharedBehavior()!=null)add(seen,npc,null,definition.sharedBehavior());if(definition.playerBehavior()!=null)for(Player player:plugin.getServer().getOnlinePlayers())add(seen,npc,player,definition.playerBehavior());}for(Key key:new ArrayList<>(entries.keySet()))if(!seen.contains(key)){Entry old=entries.remove(key);scheduler.remove(old.runtime);}}
    private void add(Set<Key> seen,NPC base,Player player,String behaviorId){Key key=new Key(base.getUniqueId(),player==null?null:player.getUniqueId());seen.add(key);Entry old=entries.get(key);BehaviorDefinition definition=plugin.registry().behaviors().get(behaviorId);if(definition==null)return;if(old!=null&&old.definition.id().equals(behaviorId)&&old.definition.hash().equals(definition.hash()))return;if(old!=null)scheduler.remove(old.runtime);BehaviorRuntime[] holder=new BehaviorRuntime[1];Environment env=new Environment(base,player,definition,()->holder[0]);BehaviorRuntime runtime=new BehaviorRuntime(definition,plugin.registry().behaviors(),env,64,30_000);holder[0]=runtime;PersistKey pk=persistKey(base,player);SqliteStore.BehaviorRow saved=persisted.get(pk);if(saved!=null&&saved.behavior().equals(behaviorId))runtime.restore(new BehaviorRuntime.Snapshot(saved.progress(),saved.deadlines(),saved.blackboard(),saved.anchor(),saved.visible(),saved.checkpoint()));entries.put(key,new Entry(base,player,definition,runtime));scheduler.add(runtime);}
    private void removePlayer(UUID id){for(Key key:new ArrayList<>(entries.keySet()))if(id.equals(key.player)){Entry e=entries.remove(key);scheduler.remove(e.runtime);}}
    private void scanProximity(){Set<Key> current=new HashSet<>();for(NPC npc:CitizensAPI.getNPCRegistry()){PersonaTrait trait=npc.getTraitNullable(PersonaTrait.class);if(trait==null||!trait.bound()||trait.projection()||!npc.isSpawned())continue;for(Player player:plugin.getServer().getOnlinePlayers())if(player.getWorld().equals(npc.getEntity().getWorld())&&player.getLocation().distanceSquared(npc.getEntity().getLocation())<=proximitySquared){Key key=new Key(npc.getUniqueId(),player.getUniqueId());current.add(key);if(!nearby.contains(key))wake(npc,player,"proximity-enter",Map.of());}}for(Key key:nearby)if(!current.contains(key)){NPC npc=CitizensAPI.getNPCRegistry().getByUniqueId(key.base);Player player=plugin.getServer().getPlayer(key.player);if(npc!=null&&player!=null)wake(npc,player,"proximity-exit",Map.of());}nearby.clear();nearby.addAll(current);}
    private NPC base(NPC npc){PersonaTrait t=npc.getTraitNullable(PersonaTrait.class);if(t!=null&&t.projection()&&t.baseNpc()!=null){NPC found=CitizensAPI.getNPCRegistry().getByUniqueId(t.baseNpc());if(found!=null)return found;}return npc;}
    private void capture(){for(Entry e:entries.values()){BehaviorRuntime.Snapshot s=e.runtime.snapshot();PersistKey key=persistKey(e.base,e.player);persisted.put(key,new SqliteStore.BehaviorRow(key.scope,key.player,key.npc,key.instance,e.definition.id(),e.definition.hash(),s.anchor(),s.visible(),s.checkpoint(),s.progress(),s.deadlines(),s.blackboard()));}}
    private PersistKey persistKey(NPC base,Player player){PersonaTrait t=base.getTrait(PersonaTrait.class);return new PersistKey(player==null?"shared":"player",player==null?"":player.getUniqueId().toString(),t.definitionId(),t.instanceId()==null?base.getUniqueId().toString():t.instanceId());}
    @Override public void close(){flush(true);entries.values().forEach(e->scheduler.remove(e.runtime));entries.clear();projections.close();}

    private final class Environment implements BehaviorRuntime.Environment {
        private final NPC base;private final Player player;private final BehaviorDefinition definition;private final java.util.function.Supplier<BehaviorRuntime> runtime;
        Environment(NPC base,Player player,BehaviorDefinition definition,java.util.function.Supplier<BehaviorRuntime> runtime){this.base=base;this.player=player;this.definition=definition;this.runtime=runtime;}
        public long now(){return System.currentTimeMillis();}
        public boolean condition(BehaviorDefinition.BehaviorNode node,BehaviorEvent event){String type=string(node,"condition","");if(type.equals("event")){String expected=string(node,"event",string(node,"name",""));return event!=null&&event.type().equals(expected);}if(type.equals("memory")){var value=memories.get(memoryPlayer(node),npcId(),instance(),string(node,"key","")).orElse(null);if(value==null)return false;String op=string(node,"operator","equals"),expected=string(node,"value","true");return compare(value,op,expected);}if(player!=null){var state=plugin.states().require(player);if(type.equals("flag"))return state!=null&&state.flags().getOrDefault(string(node,"name",""),false)==bool(node,"value",true);if(type.equals("permission"))return player.hasPermission(string(node,"permission",""));if(type.equals("world"))return player.getWorld().getName().equals(string(node,"world",""));if(type.equals("chance"))return ThreadLocalRandom.current().nextDouble()<number(node,"chance",0);if(type.equals("item-count")){var material=org.bukkit.Material.matchMaterial(string(node,"material",""));return material!=null&&player.getInventory().all(material).values().stream().mapToInt(org.bukkit.inventory.ItemStack::getAmount).sum()>=number(node,"amount",1);}if(type.equals("quest-state"))return state!=null&&state.questState(string(node,"quest","")).name().equalsIgnoreCase(string(node,"state","").replace('-','_'));if(type.equals("variable")&&state!=null){String actual=state.variables().getOrDefault(string(node,"name",""),"");return string(node,"operator","equals").equals("not-equals")?!actual.equals(string(node,"value","")):actual.equals(string(node,"value",""));}}var handler=plugin.api().handler(ExpansionTypes.BehaviorCondition.class,type).orElse(null);return handler!=null&&handler.test(context(event),node.options());}
        public CompletionStage<BehaviorStatus> action(BehaviorDefinition.BehaviorNode node){String action=string(node,"action","");try{return switch(action){case "remember"->completed(remember(node));case "adjust-memory"->completed(adjust(node));case "forget"->completed(forget(node));case "set-anchor"->{runtime.get().anchor(string(node,"anchor",null));yield completed(BehaviorStatus.SUCCESS);}case "set-visible"->{runtime.get().visible(bool(node,"visible",true));yield completed(BehaviorStatus.SUCCESS);}case "logical-travel"->travel(node);case "navigate"->navigate(node);case "look"->{NPC actor=actor();Location target=location(string(node,"anchor",null));if(actor!=null&&target!=null)actor.faceLocation(target);yield completed(target==null?BehaviorStatus.FAILURE:BehaviorStatus.SUCCESS);}case "wander"->completed(wander(node));case "script"->script(node);case "command"->command(node);default->{var extension=plugin.api().handler(ExpansionTypes.BehaviorAction.class,action).orElse(null);yield extension==null?completed(BehaviorStatus.FAILURE):extension.execute(context(null),node.options());}};}catch(RuntimeException e){plugin.getLogger().warning("Behavior action "+action+" failed: "+e.getMessage());return completed(BehaviorStatus.FAILURE);}}
        public void cancel(BehaviorDefinition.BehaviorNode node){String action=string(node,"action","");if(action.equals("navigate")){NPC actor=actor();if(actor!=null)actor.getNavigator().cancelNavigation();}plugin.api().handler(ExpansionTypes.BehaviorAction.class,action).ifPresent(x->x.cancel(context(null)));}
        private BehaviorStatus remember(BehaviorDefinition.BehaviorNode n){NpcMemoryService.Type type=NpcMemoryService.Type.valueOf(string(n,"value-type",infer(n.options().get("value"))).toUpperCase(Locale.ROOT));memories.set(memoryPlayer(n),npcId(),instance(),string(n,"key",""),type,n.options().get("value"),ttl(n),"behavior:"+definition.id()+"/"+n.id());return BehaviorStatus.SUCCESS;}
        private BehaviorStatus adjust(BehaviorDefinition.BehaviorNode n){memories.adjust(memoryPlayer(n),npcId(),instance(),string(n,"key",""),number(n,"amount",0),ttl(n),"behavior:"+definition.id()+"/"+n.id());return BehaviorStatus.SUCCESS;}
        private BehaviorStatus forget(BehaviorDefinition.BehaviorNode n){memories.forget(memoryPlayer(n),npcId(),instance(),string(n,"key",""));return BehaviorStatus.SUCCESS;}
        private CompletionStage<BehaviorStatus> travel(BehaviorDefinition.BehaviorNode n){String destination=string(n,"destination",string(n,"anchor",null));Duration duration=Durations.parse(n.options().getOrDefault("duration","0s"));long started=((Number)runtime.get().blackboard().computeIfAbsent(n.id()+".started",x->now())).longValue();runtime.get().blackboard().put(n.id()+".source",Objects.toString(runtime.get().anchor(),""));runtime.get().blackboard().put(n.id()+".destination",destination);long remaining=Math.max(0,started+duration.toMillis()-now());CompletableFuture<BehaviorStatus> result=new CompletableFuture<>();plugin.getServer().getScheduler().runTaskLater(plugin,()->{runtime.get().anchor(destination);runtime.get().blackboard().keySet().removeIf(x->x.startsWith(n.id()+"."));result.complete(BehaviorStatus.SUCCESS);},Math.max(1,(long)Math.ceil(remaining/50d)));return result;}
        private CompletionStage<BehaviorStatus> navigate(BehaviorDefinition.BehaviorNode n){NPC actor=actor();Location target=location(string(n,"anchor",null));if(actor==null||!actor.isSpawned()||target==null)return completed(BehaviorStatus.FAILURE);actor.getNavigator().setTarget(target);CompletableFuture<BehaviorStatus> result=new CompletableFuture<>();org.bukkit.scheduler.BukkitTask[] task=new org.bukkit.scheduler.BukkitTask[1];task[0]=plugin.getServer().getScheduler().runTaskTimer(plugin,()->{if(!actor.getNavigator().isNavigating()){task[0].cancel();result.complete(actor.getStoredLocation()!=null&&actor.getStoredLocation().getWorld().equals(target.getWorld())&&actor.getStoredLocation().distanceSquared(target)<4?BehaviorStatus.SUCCESS:BehaviorStatus.FAILURE);}},1,1);return result;}
        private BehaviorStatus wander(BehaviorDefinition.BehaviorNode n){NPC actor=actor();if(actor==null||!actor.isSpawned())return BehaviorStatus.FAILURE;double radius=number(n,"radius",5);Location at=actor.getStoredLocation().clone().add(ThreadLocalRandom.current().nextDouble(-radius,radius),0,ThreadLocalRandom.current().nextDouble(-radius,radius));actor.getNavigator().setTarget(at);return BehaviorStatus.SUCCESS;}
        private CompletionStage<BehaviorStatus> script(BehaviorDefinition.BehaviorNode n){if(player==null)return completed(BehaviorStatus.FAILURE);List<Content.Step> steps=plugin.registry().scripts().get(string(n,"script",""));if(steps==null)return completed(BehaviorStatus.FAILURE);return plugin.scripts().run(steps,new EffectExecutor.Context(player,actor(),plugin.registry().npcs().get(npcId()),null,null,null,0,0)).thenApply(x->x.kind()==nu.miguel.persona.script.ScriptEngine.Kind.CONTINUE?BehaviorStatus.SUCCESS:BehaviorStatus.FAILURE);}
        private CompletionStage<BehaviorStatus> command(BehaviorDefinition.BehaviorNode n){if(player==null)return completed(BehaviorStatus.FAILURE);String type=nu.miguel.persona.api.PersonaApi.canonical(string(n,"command",""));Map<String,Object> options=new LinkedHashMap<>(n.options());options.keySet().removeAll(Set.of("action","command"));Content.Command command=new Content.Command(type,options,List.of(),List.of());return plugin.scripts().run(List.of(command),new EffectExecutor.Context(player,actor(),plugin.registry().npcs().get(npcId()),null,null,null,0,0)).thenApply(x->x.kind()==nu.miguel.persona.script.ScriptEngine.Kind.CONTINUE?BehaviorStatus.SUCCESS:BehaviorStatus.FAILURE);}
        private NPC actor(){if(player==null)return base;ProjectionManager.Presentation p=projections.inspect(player,base);return p.projection()!=null&&p.projection().isSpawned()?p.projection():runtime.get().anchor()==null?base:null;}
        private Location location(String anchor){if(anchor==null)return null;Content.Npc n=plugin.registry().npcs().get(npcId());Content.Anchor a=n==null?null:n.anchors().get(anchor);var world=a==null?null:plugin.getServer().getWorld(a.world());return world==null?null:new Location(world,a.x(),a.y(),a.z(),a.yaw(),a.pitch());}
        private BehaviorContext context(BehaviorEvent event){return new BehaviorContext(definition.scope(),Optional.ofNullable(player),npcId(),instance(),Optional.ofNullable(actor()),Optional.ofNullable(event),memories,runtime.get().blackboard());}
        private UUID memoryPlayer(BehaviorDefinition.BehaviorNode n){String scope=string(n,"scope",definition.scope()==BehaviorScope.SHARED?"global":"player");return scope.equals("global")||scope.equals("npc")?null:player==null?null:player.getUniqueId();}
        private String npcId(){return base.getTrait(PersonaTrait.class).definitionId();}private String instance(){String value=base.getTrait(PersonaTrait.class).instanceId();return value==null?base.getUniqueId().toString():value;}
    }
    private static boolean compare(NpcMemoryService.Value v,String op,String expected){if(v.type()==NpcMemoryService.Type.NUMBER){double a=v.numberValue(),b=Double.parseDouble(expected);return switch(op){case "greater-than"->a>b;case "greater-than-or-equal"->a>=b;case "less-than"->a<b;case "less-than-or-equal"->a<=b;case "not-equals"->a!=b;default->a==b;};}String actual=String.valueOf(v.value());return op.equals("not-equals")?!actual.equalsIgnoreCase(expected):op.equals("contains")?actual.contains(expected):actual.equalsIgnoreCase(expected);}
    private static String string(BehaviorDefinition.BehaviorNode n,String key,String fallback){Object v=n.options().get(key);return v==null?fallback:String.valueOf(v);}private static boolean bool(BehaviorDefinition.BehaviorNode n,String key,boolean fallback){Object v=n.options().get(key);return v==null?fallback:v instanceof Boolean b?b:Boolean.parseBoolean(String.valueOf(v));}private static double number(BehaviorDefinition.BehaviorNode n,String key,double fallback){Object v=n.options().get(key);return v==null?fallback:v instanceof Number x?x.doubleValue():Double.parseDouble(String.valueOf(v));}
    private static Duration ttl(BehaviorDefinition.BehaviorNode n){Object raw=n.options().get("ttl");return raw==null?null:Durations.parse(raw);}private static String infer(Object value){if(value instanceof Boolean)return "boolean";if(value instanceof Number)return "number";return "string";}private static CompletionStage<BehaviorStatus> completed(BehaviorStatus s){return CompletableFuture.completedFuture(s);}
}
