package nu.miguel.persona.behavior;

import net.citizensnpcs.api.CitizensAPI;
import net.citizensnpcs.api.npc.NPC;
import nu.miguel.persona.Main;
import nu.miguel.persona.api.BehaviorContext;
import nu.miguel.persona.api.CancellationToken;
import nu.miguel.persona.api.ExpansionTypes;
import nu.miguel.persona.api.NpcMemoryService;
import nu.miguel.persona.citizens.PersonaTrait;
import nu.miguel.persona.citizens.ProjectionManager;
import nu.miguel.persona.content.Content;
import nu.miguel.persona.content.Durations;
import nu.miguel.persona.script.EffectExecutor;
import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.event.player.PlayerTeleportEvent;
import org.bukkit.scheduler.BukkitTask;

import java.time.Duration;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;
import nu.miguel.persona.state.SqliteStore;

/** Owns shared and player/NPC runtimes and bridges native actions to Bukkit/Citizens. */
public final class BehaviorService implements AutoCloseable {
    private record Key(UUID base,UUID player) {}
    private record Entry(NPC base,Player player,BehaviorDefinition definition,BehaviorRuntime runtime,Environment environment) {}
    private record PersistKey(String scope,String player,String npc,String instance) {}
    private final Main plugin;private final NpcMemoryService memories;private final ProjectionManager projections;private final BehaviorScheduler scheduler=new BehaviorScheduler();private final Map<Key,Entry> entries=new LinkedHashMap<>();
    private final int evaluationLimit,tickCadence;private final long nanosLimit;private int ticks;private long generation;
    private volatile int lastEvaluated;private volatile long lastTickNanos;
    private final Set<Key> nearby=new HashSet<>();private final double proximitySquared;
    private final Map<PersistKey,SqliteStore.BehaviorRow> persisted=new ConcurrentHashMap<>(),saved=new ConcurrentHashMap<>();
    private final Map<Key,String> projectionStates=new HashMap<>();
    public record Usage(long calls,long totalNanos,long maximumNanos){public double totalMillis(){return totalNanos/1_000_000d;}public double maximumMillis(){return maximumNanos/1_000_000d;}}
    public record Orphan(String scope,String player,String npcDefinition,String instance,String behavior,String reason) {}
    public record RuntimeSummary(String npcDefinition,String instance,String player,String behavior,String treeHash,boolean paused,
                                 List<String> runningPath,String checkpoint,long wakeAt,Set<String> blackboardKeys,int inbox,long droppedEvents,
                                 Map<String,Long> deadlines,List<BehaviorRuntime.TraceEntry> trace,List<BehaviorEvent> events,
                                 NavigationSummary navigation) {}
    public record NavigationSummary(String target,long startedAt,String status,String result,String reason) {
        public static final NavigationSummary IDLE=new NavigationSummary("",0,"IDLE","","");
    }
    public record LiveMetrics(int evaluated,long tickNanos,int wakeQueue,int persistenceQueue){}
    public record DebugFilter(String npcInstance,String player,String behavior,String node) {public boolean empty(){return npcInstance==null&&player==null&&behavior==null&&node==null;}}
    private static final class Metric {long calls,total,max; synchronized void add(long nanos){calls++;total+=nanos;max=Math.max(max,nanos);} synchronized Usage snapshot(){return new Usage(calls,total,max);}}
    private final Map<String,Metric> usage=new ConcurrentHashMap<>();private volatile DebugFilter debugFilter=new DebugFilter(null,null,null,null);
    private final double slowMillis;
    public BehaviorService(Main plugin,NpcMemoryService memories,ProjectionManager projections){this.plugin=plugin;this.memories=memories;this.projections=projections;evaluationLimit=plugin.getConfig().getInt("behavior.scheduler.node-evaluations",5000);tickCadence=Math.max(1,plugin.getConfig().getInt("behavior.tick-cadence",1));nanosLimit=(long)(plugin.getConfig().getDouble("behavior.scheduler.milliseconds",4)*1_000_000);slowMillis=Math.max(0,plugin.getConfig().getDouble("behavior.diagnostics.slow-milliseconds",5));double proximity=plugin.getConfig().getDouble("behavior.senses.proximity-range",16);proximitySquared=proximity*proximity;for(SqliteStore.BehaviorRow row:plugin.store().loadBehaviorRuntimes().join()){PersistKey key=new PersistKey(row.scope(),row.player(),row.npcDefinition(),row.instance());persisted.put(key,row);saved.put(key,row);}}
    public void tick(){long started=System.nanoTime();int current=ticks++;if(current%20==0){discover();refreshQuestPriorities();}if(current%10==0)scanProximity();if(current%tickCadence==0)lastEvaluated=scheduler.tick(evaluationLimit,nanosLimit);for(Entry e:entries.values())if(e.player!=null)projections.apply(e.player,e.base,e.runtime.anchor(),e.runtime.position(),e.runtime.visible(),false);projections.tick();emitProjectionTransitions();syncPresentationPositions();lastTickNanos=System.nanoTime()-started;}
    public void reload(){syncPresentationPositions();capture();generation++;cancelNavigators();entries.values().forEach(e->scheduler.remove(e.runtime));entries.clear();discover();flush(true);}
    public void flush(boolean synchronous){capture();Map<PersistKey,SqliteStore.BehaviorRow> dirty=new LinkedHashMap<>();persisted.forEach((key,row)->{if(!row.equals(saved.get(key)))dirty.put(key,row);});if(dirty.isEmpty())return;CompletableFuture<Void> future=plugin.store().saveBehaviorRuntimes(new ArrayList<>(dirty.values())).thenRun(()->saved.putAll(dirty));if(synchronous)future.join();}
    public void wake(NPC npc,Player player,String type,Map<String,Object> data){NPC base=base(npc);if(!entries.containsKey(new Key(base.getUniqueId(),null))&&!entries.containsKey(new Key(base.getUniqueId(),player==null?null:player.getUniqueId())))discover();BehaviorEvent event=new BehaviorEvent(type,Instant.now(),data);Entry shared=entries.get(new Key(base.getUniqueId(),null));if(shared!=null)shared.runtime.signal(event);if(player!=null){Entry own=entries.get(new Key(base.getUniqueId(),player.getUniqueId()));if(own!=null)own.runtime.signal(event);}}
    public void actorLifecycle(NPC npc,String type,Map<String,Object> data){NPC target=base(npc);discover();for(var item:entries.entrySet())if(item.getKey().base.equals(target.getUniqueId()))item.getValue().runtime.signal(new BehaviorEvent(type,Instant.now(),data));}
    public void playerStateChanged(Player player,String type,Map<String,Object> data){for(Entry e:entries.values())if(e.player!=null&&e.player.getUniqueId().equals(player.getUniqueId()))e.runtime.signal(new BehaviorEvent(type,Instant.now(),data));}
    public void memoryChanged(UUID player,String npcDefinition,String instance,String key,Object oldValue,Object newValue,String source){for(Entry e:entries.values()){PersonaTrait trait=e.base.getTraitNullable(PersonaTrait.class);if(trait==null||!trait.definitionId().equals(npcDefinition)||!persistKey(e.base,e.player).instance.equals(instance)||player!=null&&(e.player==null||!e.player.getUniqueId().equals(player)))continue;Map<String,Object> data=new LinkedHashMap<>();data.put("key",key);data.put("scope",player==null?"global":"player");data.put("old",oldValue==null?"<unset>":oldValue);data.put("new",newValue==null?"<unset>":newValue);data.put("source",Objects.toString(source,"unknown"));e.runtime.signal(new BehaviorEvent("memory-changed",Instant.now(),data));}}
    public int signalSelected(NPC npc,Player player,String name,Map<String,Object> data){NPC target=base(npc);int count=0;Entry shared=entries.get(new Key(target.getUniqueId(),null));if(shared!=null){shared.runtime.signal(new BehaviorEvent("signal:"+name,Instant.now(),data));count++;}if(player!=null){Entry own=entries.get(new Key(target.getUniqueId(),player.getUniqueId()));if(own!=null){own.runtime.signal(new BehaviorEvent("signal:"+name,Instant.now(),data));count++;}}return count;}
    public void playerJoined(Player player){discover();for(Entry e:entries.values())if(e.player==player)e.runtime.signal(BehaviorEvent.of("player-join"));projections.playerJoined(player);}
    public void playerQuit(Player player){syncPresentationPositions();capture();removePlayer(player.getUniqueId());flush(true);projections.playerQuit(player.getUniqueId());}
    public Optional<BehaviorRuntime> runtime(NPC npc,Player player){return Optional.ofNullable(entries.get(new Key(base(npc).getUniqueId(),player==null?null:player.getUniqueId()))).map(Entry::runtime);}
    public int controlSelected(NPC npc,Player player,String operation){NPC target=base(npc);int count=0;for(Entry entry:entries.values()){if(!entry.base.getUniqueId().equals(target.getUniqueId())||entry.player!=null&&(player==null||!entry.player.getUniqueId().equals(player.getUniqueId())))continue;switch(operation){case "pause"->entry.runtime.pause();case "resume"->entry.runtime.resume();case "restart"->entry.runtime.restart();case "wake"->entry.runtime.wake();default->throw new IllegalArgumentException("unknown behavior operation "+operation);}count++;}return count;}
    public void debug(DebugFilter filter){debugFilter=filter==null?new DebugFilter(null,null,null,null):filter;}
    public DebugFilter debug(){return debugFilter;}
    public Map<String,Usage> extensionUsage(){Map<String,Usage> result=new TreeMap<>();usage.forEach((key,value)->result.put(key,value.snapshot()));return Collections.unmodifiableMap(result);}
    public List<Orphan> orphanedRuntimes(){List<Orphan> result=new ArrayList<>();for(var item:persisted.entrySet()){PersistKey key=item.getKey();SqliteStore.BehaviorRow row=item.getValue();String reason=!plugin.registry().npcs().containsKey(key.npc)?"unknown NPC definition":!plugin.registry().behaviors().containsKey(row.behavior())?"unknown behavior definition":null;if(reason!=null)result.add(new Orphan(key.scope,key.player,key.npc,key.instance,row.behavior(),reason));}return List.copyOf(result);}
    public List<RuntimeSummary> runtimeSummaries(){List<RuntimeSummary> result=new ArrayList<>();for(Entry entry:entries.values()){PersonaTrait trait=entry.base.getTraitNullable(PersonaTrait.class);if(trait==null)continue;BehaviorRuntime runtime=entry.runtime;result.add(new RuntimeSummary(trait.definitionId(),trait.instanceId()==null?entry.base.getUniqueId().toString():trait.instanceId(),entry.player==null?"shared":entry.player.getUniqueId().toString(),runtime.behaviorId(),runtime.treeHash(),runtime.paused(),runtime.runningPath(),runtime.checkpoint(),runtime.nextWakeAt(),Set.copyOf(runtime.blackboard().keySet()),runtime.inbox().size(),runtime.droppedEvents(),Map.copyOf(runtime.deadlines()),runtime.traceHistory(),runtime.inbox(),entry.environment.navigationSummary()));}return List.copyOf(result);}
    public ProjectionManager projections(){return projections;}
    public LiveMetrics liveMetrics(){int dirty=(int)persisted.entrySet().stream().filter(entry->!entry.getValue().equals(saved.get(entry.getKey()))).count();return new LiveMetrics(lastEvaluated,lastTickNanos,scheduler.wakeQueueSize(),dirty);}
    private void discover(){Set<Key> seen=new HashSet<>();for(NPC npc:CitizensAPI.getNPCRegistry()){PersonaTrait trait=npc.getTraitNullable(PersonaTrait.class);if(trait==null||!trait.bound()||trait.projection())continue;Content.Npc definition=plugin.registry().npcs().get(trait.definitionId());if(definition==null)continue;if(definition.sharedBehavior()!=null)add(seen,npc,null,definition.sharedBehavior());if(definition.playerBehavior()!=null)for(Player player:plugin.getServer().getOnlinePlayers())add(seen,npc,player,definition.playerBehavior());}for(Key key:new ArrayList<>(entries.keySet()))if(!seen.contains(key)){Entry old=entries.remove(key);scheduler.remove(old.runtime);}}
    private void add(Set<Key> seen,NPC base,Player player,String behaviorId){Key key=new Key(base.getUniqueId(),player==null?null:player.getUniqueId());seen.add(key);Entry old=entries.get(key);BehaviorDefinition definition=plugin.registry().behaviors().get(behaviorId);if(definition==null)return;if(old!=null&&old.definition.id().equals(behaviorId)&&old.definition.hash().equals(definition.hash()))return;if(old!=null)scheduler.remove(old.runtime);BehaviorRuntime[] holder=new BehaviorRuntime[1];Environment env=new Environment(key,base,player,definition,generation,()->holder[0]);BehaviorRuntime runtime=new BehaviorRuntime(definition,plugin.registry().behaviors(),env,64,30_000);holder[0]=runtime;PersistKey pk=persistKey(base,player);SqliteStore.BehaviorRow stored=persisted.get(pk);if(stored!=null&&stored.behavior().equals(behaviorId))runtime.restore(new BehaviorRuntime.Snapshot(stored.progress(),stored.deadlines(),stored.blackboard(),stored.anchor(),stored.position(),stored.visible(),stored.checkpoint(),stored.wakeAt(),stored.nodeTypes(),stored.checkpointStructure(),stored.logicalTravel(),stored.hash()));entries.put(key,new Entry(base,player,definition,runtime,env));scheduler.add(runtime);}
    private void removePlayer(UUID id){for(Key key:new ArrayList<>(entries.keySet()))if(id.equals(key.player)){Entry e=entries.remove(key);scheduler.remove(e.runtime);}}
    private void scanProximity(){Set<Key> current=new HashSet<>();for(var item:entries.entrySet()){Key key=item.getKey();Entry e=item.getValue();if(e.player==null||!e.player.isOnline())continue;Location location=activePresentationLocation(e);if(location!=null&&e.player.getWorld().equals(location.getWorld())&&e.player.getLocation().distanceSquared(location)<=proximitySquared){current.add(key);if(!nearby.contains(key))e.runtime.signal(new BehaviorEvent("proximity-enter",Instant.now(),Map.of()));}}for(Key key:nearby)if(!current.contains(key)){Entry e=entries.get(key);if(e!=null)e.runtime.signal(new BehaviorEvent("proximity-exit",Instant.now(),Map.of()));}nearby.clear();nearby.addAll(current);}
    private void refreshQuestPriorities(){for(Entry e:entries.values())if(e.player!=null){PersonaTrait trait=e.base.getTraitNullable(PersonaTrait.class);boolean relevant=false;var state=plugin.states().require(e.player);if(trait!=null&&state!=null)for(var active:state.quests().entrySet()){Content.Quest quest=plugin.registry().quests().get(active.getKey());int phase=active.getValue().phase();if(quest==null||phase<0||phase>=quest.phases().size())continue;if(quest.phases().get(phase).objectives().stream().anyMatch(o->o.type()==Content.ObjectiveType.TALK_TO_NPC&&trait.definitionId().equals(o.npc()))){relevant=true;break;}}projections.markQuest(e.player,e.base,relevant);}}
    private Location activePresentationLocation(Entry e){ProjectionManager.Presentation p=projections.inspect(e.player,e.base);if(p.projection()!=null&&p.projection().isSpawned())return p.projection().getStoredLocation();BehaviorRuntime.LogicalPosition pos=p.position();if(pos!=null){var world=plugin.getServer().getWorld(pos.world());return world==null?null:new Location(world,pos.x(),pos.y(),pos.z(),pos.yaw(),pos.pitch());}return e.base.isSpawned()?e.base.getEntity().getLocation():null;}
    private void emitProjectionTransitions(){Set<Key> seen=new HashSet<>();for(var item:entries.entrySet()){Key key=item.getKey();Entry e=item.getValue();if(e.player==null)continue;seen.add(key);ProjectionManager.Presentation p=projections.inspect(e.player,e.base);String state=(p.projection()!=null&&p.projection().isSpawned()?"spawned:":"despawned:")+p.reason();String old=projectionStates.put(key,state);if(Objects.equals(old,state)||old==null&&!state.startsWith("spawned:"))continue;String type=state.startsWith("spawned:")&&(old==null||!old.startsWith("spawned:"))?"projection-spawn":!state.startsWith("spawned:")&&old!=null&&old.startsWith("spawned:")?"projection-despawn":"projection-lifecycle";e.runtime.signal(new BehaviorEvent(type,Instant.now(),Map.of("previous",Objects.toString(old,"none"),"current",state,"reason",p.reason())));}projectionStates.keySet().retainAll(seen);}
    private NPC base(NPC npc){PersonaTrait t=npc.getTraitNullable(PersonaTrait.class);if(t!=null&&t.projection()&&t.baseNpc()!=null){NPC found=CitizensAPI.getNPCRegistry().getByUniqueId(t.baseNpc());if(found!=null)return found;}return npc;}
    private void syncPresentationPositions(){for(Entry e:entries.values())if(e.player!=null){ProjectionManager.Presentation p=projections.inspect(e.player,e.base);if(p.position()!=null)e.runtime.position(p.position());}}
    private void cancelNavigators(){for(Entry e:entries.values())e.base.getNavigator().cancelNavigation();projections.cancelNavigations();}
    private void capture(){for(Entry e:entries.values()){BehaviorRuntime.Snapshot s=e.runtime.snapshot();PersistKey key=persistKey(e.base,e.player);persisted.put(key,new SqliteStore.BehaviorRow(key.scope,key.player,key.npc,key.instance,e.definition.id(),e.definition.hash(),s.anchor(),s.position(),s.visible(),s.checkpoint(),s.wakeAt(),s.progress(),s.deadlines(),s.blackboard(),s.nodeTypes(),s.checkpointStructure(),s.logicalTravel()));}}
    private PersistKey persistKey(NPC base,Player player){PersonaTrait t=base.getTrait(PersonaTrait.class);return new PersistKey(player==null?"shared":"player",player==null?"":player.getUniqueId().toString(),t.definitionId(),t.instanceId()==null?base.getUniqueId().toString():t.instanceId());}
    @Override public void close(){syncPresentationPositions();flush(true);generation++;cancelNavigators();entries.values().forEach(e->scheduler.remove(e.runtime));entries.clear();projections.close();}

    private final class Environment implements BehaviorRuntime.Environment {
        private record ExtensionExecution(CancellationToken token,ExpansionTypes.BehaviorAction handler,BehaviorContext context,java.util.concurrent.atomic.AtomicBoolean cancelled) {}
        private final Key key;private final NPC base;private final Player player;private final BehaviorDefinition definition;private final long createdGeneration;private final java.util.function.Supplier<BehaviorRuntime> runtime;private final Map<String,NavigationOperation> navigations=new HashMap<>();private final Map<String,BukkitTask> tasks=new HashMap<>();private final Map<String,CompletableFuture<BehaviorStatus>> taskResults=new HashMap<>();private final Map<String,ExtensionExecution> extensionExecutions=new HashMap<>();private NavigationSummary lastNavigation=NavigationSummary.IDLE;
        Environment(Key key,NPC base,Player player,BehaviorDefinition definition,long createdGeneration,java.util.function.Supplier<BehaviorRuntime> runtime){this.key=key;this.base=base;this.player=player;this.definition=definition;this.createdGeneration=createdGeneration;this.runtime=runtime;}
        NavigationSummary navigationSummary(){BehaviorRuntime.LogicalTravel travel=runtime.get().logicalTravel();if(travel!=null)return new NavigationSummary(travel.destination(),travel.startedAt(),"RUNNING","","logical-travel");if(!navigations.isEmpty()){NavigationOperation operation=navigations.values().iterator().next();return new NavigationSummary(operation.destination,operation.startedAt,"RUNNING","","pathfinding");}return lastNavigation;}
        public long now(){return System.currentTimeMillis();}
        public boolean condition(BehaviorDefinition.BehaviorNode node,BehaviorEvent event){String type=string(node,"condition","");long started=System.nanoTime();try{if(type.equals("event")){String expected=string(node,"event",string(node,"name",""));return event!=null&&event.type().equals(expected);}if(type.equals("memory")){var value=memories.get(memoryPlayer(node),npcId(),instance(),string(node,"key","")).orElse(null);if(value==null)return false;String op=string(node,"operator","equals"),expected=string(node,"value","true");return compare(value,op,expected);}if(player!=null){var state=plugin.states().require(player);if(type.equals("flag"))return state!=null&&state.flags().getOrDefault(string(node,"name",""),false)==bool(node,"value",true);if(type.equals("permission"))return player.hasPermission(string(node,"permission",""));if(type.equals("world"))return player.getWorld().getName().equals(string(node,"world",""));if(type.equals("chance"))return ThreadLocalRandom.current().nextDouble()<number(node,"chance",0);if(type.equals("item-count")){var material=org.bukkit.Material.matchMaterial(string(node,"material",""));return material!=null&&player.getInventory().all(material).values().stream().mapToInt(org.bukkit.inventory.ItemStack::getAmount).sum()>=number(node,"amount",1);}if(type.equals("quest-state"))return state!=null&&state.questState(string(node,"quest","")).name().equalsIgnoreCase(string(node,"state","").replace('-','_'));if(type.equals("variable")&&state!=null){String actual=state.variables().getOrDefault(string(node,"name",""),"");Content.Comparison operator=Content.Comparison.valueOf(string(node,"operator","equals").toUpperCase(Locale.ROOT).replace('-','_'));return nu.miguel.persona.quest.ConditionEvaluator.compare(actual,operator,string(node,"value",""));}}var handler=plugin.api().handler(ExpansionTypes.BehaviorCondition.class,type).orElse(null);return handler!=null&&handler.test(context(event),node.options());}finally{timing("condition",type,node,System.nanoTime()-started);}}
        public CompletionStage<BehaviorStatus> action(BehaviorDefinition.BehaviorNode node){return action(definition.id(),node);}
        public CompletionStage<BehaviorStatus> action(String behaviorId,BehaviorDefinition.BehaviorNode node){String action=string(node,"action","");long started=System.nanoTime();try{CompletionStage<BehaviorStatus> result=switch(action){case "remember"->completed(remember(behaviorId,node));case "adjust-memory"->completed(adjust(behaviorId,node));case "forget"->completed(forget(node));case "set-anchor"->completed(setAnchor(node));case "begin-private-presentation"->completed(beginPrivate());case "set-visible"->{runtime.get().visible(bool(node,"visible",true));yield completed(BehaviorStatus.SUCCESS);}case "signal"->{runtime.get().signal(new BehaviorEvent("signal:"+string(node,"name",""),Instant.now(),Map.of()));yield completed(BehaviorStatus.SUCCESS);}case "logical-travel"->travel(behaviorId,node);case "navigate"->navigate(behaviorId,node,false);case "private-navigate"->navigate(behaviorId,node,true);case "look"->{NPC actor=actor();Location target=location(string(node,"anchor",null));if(actor!=null&&target!=null)actor.faceLocation(target);yield completed(target==null?BehaviorStatus.FAILURE:BehaviorStatus.SUCCESS);}case "wander"->completed(wander(node));case "script"->script(node);case "command"->command(node);default->{var extension=plugin.api().handler(ExpansionTypes.BehaviorAction.class,action).orElse(null);if(extension==null)yield completed(BehaviorStatus.FAILURE);String executionKey=stateKey(behaviorId,node);CancellationToken token=new CancellationToken(callback->{if(org.bukkit.Bukkit.isPrimaryThread())callback.run();else plugin.getServer().getScheduler().runTask(plugin,callback);});BehaviorContext context=context(null);ExtensionExecution execution=new ExtensionExecution(token,extension,context,new java.util.concurrent.atomic.AtomicBoolean());extensionExecutions.put(executionKey,execution);CompletionStage<BehaviorStatus> stage=extension.execute(context,node.options(),token);stage.whenComplete((value,error)->extensionExecutions.remove(executionKey,execution));yield stage;}};result.whenComplete((value,error)->timing("action",action,node,System.nanoTime()-started));return result;}catch(RuntimeException e){timing("action",action,node,System.nanoTime()-started);plugin.getLogger().warning("Behavior action "+action+" failed: "+e.getMessage());return completed(BehaviorStatus.FAILURE);}}
        public void cancel(BehaviorDefinition.BehaviorNode node){cancel(definition.id(),node);}
        public void cancel(String behaviorId,BehaviorDefinition.BehaviorNode node){String key=stateKey(behaviorId,node);NavigationOperation navigation=navigations.remove(key);if(navigation!=null)navigation.cancel(true);BukkitTask task=tasks.remove(key);if(task!=null)task.cancel();CompletableFuture<BehaviorStatus> result=taskResults.remove(key);if(result!=null)result.complete(BehaviorStatus.FAILURE);ExtensionExecution execution=extensionExecutions.remove(key);if(execution!=null&&execution.cancelled.compareAndSet(false,true)){try{execution.token.cancel();}catch(RuntimeException e){plugin.getLogger().warning("Extension cancellation callback failed: "+e.getMessage());}try{execution.handler.cancel(execution.context);}catch(RuntimeException e){plugin.getLogger().warning("Extension legacy cancellation failed: "+e.getMessage());}}}
        public void wake(){if(active())scheduler.wake(runtime.get());}
        private BehaviorStatus remember(String behaviorId,BehaviorDefinition.BehaviorNode n){NpcMemoryService.Type type=NpcMemoryService.Type.valueOf(string(n,"value-type",infer(n.options().get("value"))).toUpperCase(Locale.ROOT));memories.set(memoryPlayer(n),npcId(),instance(),string(n,"key",""),type,n.options().get("value"),ttl(n),"behavior:"+behaviorId+"/"+n.id());return BehaviorStatus.SUCCESS;}
        private BehaviorStatus adjust(String behaviorId,BehaviorDefinition.BehaviorNode n){memories.adjust(memoryPlayer(n),npcId(),instance(),string(n,"key",""),number(n,"amount",0),ttl(n),"behavior:"+behaviorId+"/"+n.id());return BehaviorStatus.SUCCESS;}
        private BehaviorStatus forget(BehaviorDefinition.BehaviorNode n){memories.forget(memoryPlayer(n),npcId(),instance(),string(n,"key",""));return BehaviorStatus.SUCCESS;}
        private BehaviorStatus setAnchor(BehaviorDefinition.BehaviorNode n){String anchor=string(n,"anchor",null);boolean changed=!Objects.equals(runtime.get().anchor(),anchor)||(anchor==null&&runtime.get().position()!=null);if(!changed)return BehaviorStatus.SUCCESS;runtime.get().anchor(anchor);runtime.get().position(null);if(player!=null){if(anchor==null)projections.inherit(player,base);else projections.begin(player,base,anchor,null);}return BehaviorStatus.SUCCESS;}
        private BehaviorStatus beginPrivate(){Location at=base.isSpawned()?base.getEntity().getLocation():base.getStoredLocation();if(player==null||at==null)return BehaviorStatus.FAILURE;BehaviorRuntime.LogicalPosition position=ProjectionManager.position(at);runtime.get().anchor(null);runtime.get().position(position);runtime.get().visible(true);projections.begin(player,base,null,position);return BehaviorStatus.SUCCESS;}
        private CompletionStage<BehaviorStatus> travel(String behaviorId,BehaviorDefinition.BehaviorNode n){String key=stateKey(behaviorId,n),destination=string(n,"destination",string(n,"anchor",null));Duration duration=Durations.parse(n.options().getOrDefault("duration","0s"));BehaviorRuntime.LogicalTravel travel=runtime.get().logicalTravel();if(travel==null||!travel.behaviorId().equals(behaviorId)||!travel.nodeId().equals(n.id())){travel=new BehaviorRuntime.LogicalTravel(behaviorId,n.id(),runtime.get().anchor(),destination,now(),duration.toMillis());runtime.get().logicalTravel(travel);}long remaining=Math.max(0,travel.completesAt()-now());BehaviorRuntime.LogicalTravel expected=travel;CompletableFuture<BehaviorStatus> result=new CompletableFuture<>();taskResults.put(key,result);BukkitTask task=plugin.getServer().getScheduler().runTaskLater(plugin,()->{tasks.remove(key);taskResults.remove(key);if(!active()){result.complete(BehaviorStatus.FAILURE);return;}runtime.get().anchor(expected.destination());runtime.get().position(null);if(player!=null)projections.begin(player,base,expected.destination(),null);if(Objects.equals(runtime.get().logicalTravel(),expected))runtime.get().logicalTravel(null);result.complete(BehaviorStatus.SUCCESS);},Math.max(1,(long)Math.ceil(remaining/50d)));tasks.put(key,task);return result;}
        private CompletionStage<BehaviorStatus> navigate(String behaviorId,BehaviorDefinition.BehaviorNode n,boolean privateNavigation){String destination=string(n,"destination",string(n,"anchor",null));Location target=location(destination);if(target==null){navigationEvent("navigation-failure",destination,"destination-world-unavailable",privateNavigation);return completed(BehaviorStatus.FAILURE);}if(privateNavigation){if(player==null)return completed(BehaviorStatus.FAILURE);ProjectionManager.Presentation presentation=projections.inspect(player,base);BehaviorRuntime.LogicalPosition start=presentation.position()==null?runtime.get().position():presentation.position();if(start==null){Location at=base.isSpawned()?base.getEntity().getLocation():base.getStoredLocation();if(at==null){navigationEvent("navigation-failure",destination,"base-actor-unavailable",true);return completed(BehaviorStatus.FAILURE);}start=ProjectionManager.position(at);}if(presentation.position()==null)projections.begin(player,base,destination,start);runtime.get().anchor(destination);runtime.get().position(start);runtime.get().visible(true);}else{NPC actor=actor();if(actor==null||!actor.isSpawned()){navigationEvent("navigation-failure",destination,"actor-unavailable",false);return completed(BehaviorStatus.FAILURE);}}String key=stateKey(behaviorId,n);NavigationOperation operation=new NavigationOperation(key,n,destination,target,privateNavigation);navigations.put(key,operation);operation.start();return operation.result;}
        private BehaviorStatus wander(BehaviorDefinition.BehaviorNode n){NPC actor=actor();if(actor==null||!actor.isSpawned())return BehaviorStatus.FAILURE;double radius=number(n,"radius",5);Location at=actor.getStoredLocation().clone().add(ThreadLocalRandom.current().nextDouble(-radius,radius),0,ThreadLocalRandom.current().nextDouble(-radius,radius));actor.getNavigator().setTarget(at);return BehaviorStatus.SUCCESS;}
        private CompletionStage<BehaviorStatus> script(BehaviorDefinition.BehaviorNode n){if(player==null)return completed(BehaviorStatus.FAILURE);List<Content.Step> steps=plugin.registry().scripts().get(string(n,"script",""));if(steps==null)return completed(BehaviorStatus.FAILURE);return plugin.scripts().run(steps,new EffectExecutor.Context(player,actor(),plugin.registry().npcs().get(npcId()),null,null,null,0,0)).thenApply(x->x.kind()==nu.miguel.persona.script.ScriptEngine.Kind.CONTINUE?BehaviorStatus.SUCCESS:BehaviorStatus.FAILURE);}
        private CompletionStage<BehaviorStatus> command(BehaviorDefinition.BehaviorNode n){if(player==null)return completed(BehaviorStatus.FAILURE);String type=nu.miguel.persona.api.PersonaApi.canonical(string(n,"command",""));Map<String,Object> options=new LinkedHashMap<>(n.options());options.keySet().removeAll(Set.of("action","command"));Content.Command command=new Content.Command(type,options,List.of(),List.of());return plugin.scripts().run(List.of(command),new EffectExecutor.Context(player,actor(),plugin.registry().npcs().get(npcId()),null,null,null,0,0)).thenApply(x->x.kind()==nu.miguel.persona.script.ScriptEngine.Kind.CONTINUE?BehaviorStatus.SUCCESS:BehaviorStatus.FAILURE);}
        private boolean active(){Entry current=entries.get(key);return createdGeneration==generation&&current!=null&&current.runtime()==runtime.get();}
        private void navigationEvent(String type,String destination,String reason,boolean privateNavigation){if(!active())return;Map<String,Object> data=new LinkedHashMap<>();data.put("destination",destination);data.put("private",privateNavigation);if(reason!=null)data.put("reason",reason);runtime.get().signal(new BehaviorEvent(type,Instant.now(),Map.copyOf(data)));}
        private NPC actor(){if(player==null)return base;ProjectionManager.Presentation p=projections.inspect(player,base);return p.projection()!=null&&p.projection().isSpawned()?p.projection():runtime.get().anchor()==null&&runtime.get().position()==null&&runtime.get().visible()?base:null;}
        private Location location(String anchor){if(anchor==null)return null;Content.Npc n=plugin.registry().npcs().get(npcId());Content.Anchor a=n==null?null:n.anchors().get(anchor);var world=a==null?null:plugin.getServer().getWorld(a.world());return world==null?null:new Location(world,a.x(),a.y(),a.z(),a.yaw(),a.pitch());}
        private BehaviorContext context(BehaviorEvent event){return new BehaviorContext(definition.scope(),Optional.ofNullable(player),npcId(),instance(),Optional.ofNullable(actor()),Optional.ofNullable(event),memories,runtime.get().blackboard());}
        private UUID memoryPlayer(BehaviorDefinition.BehaviorNode n){String scope=string(n,"scope",definition.scope()==BehaviorScope.SHARED?"global":"player");return scope.equals("global")||scope.equals("npc")?null:player==null?null:player.getUniqueId();}
        private String npcId(){return base.getTrait(PersonaTrait.class).definitionId();}private String instance(){String value=base.getTrait(PersonaTrait.class).instanceId();return value==null?base.getUniqueId().toString():value;}
        private void timing(String kind,String type,BehaviorDefinition.BehaviorNode node,long nanos){if(type.contains(":"))usage.computeIfAbsent(kind+":"+type,x->new Metric()).add(nanos);DebugFilter filter=debugFilter;boolean matches=(filter.npcInstance()==null||filter.npcInstance().equals(instance()))&&(filter.player()==null||player!=null&&(filter.player().equalsIgnoreCase(player.getName())||filter.player().equals(player.getUniqueId().toString())))&&(filter.behavior()==null||filter.behavior().equals(definition.id()))&&(filter.node()==null||filter.node().equals(node.id()));if(matches&&(!filter.empty()||nanos/1_000_000d>=slowMillis))plugin.getLogger().info("Behavior timing npc="+instance()+" player="+(player==null?"shared":player.getUniqueId())+" behavior="+definition.id()+" node="+node.id()+" "+kind+"="+type+" duration-ms="+String.format(Locale.ROOT,"%.3f",nanos/1_000_000d));}

        private final class NavigationOperation {
            private final String operationKey;
            private final BehaviorDefinition.BehaviorNode node;
            private final String destination;
            private final Location target;
            private final boolean privateNavigation;
            private final CompletableFuture<BehaviorStatus> result=new CompletableFuture<>();
            private final long startedAt=now();
            private final double arrivalDistance;
            private final float speed,pathfindingRange;
            private final long stuckMillis;
            private final String stuckAction;
            private final int stuckRetries;
            private BukkitTask task;
            private double bestDistance=Double.MAX_VALUE;
            private long lastProgress=now();
            private int retries;

            NavigationOperation(String operationKey,BehaviorDefinition.BehaviorNode node,String destination,Location target,boolean privateNavigation){
                this.operationKey=operationKey;this.node=node;this.destination=destination;this.target=target;this.privateNavigation=privateNavigation;
                arrivalDistance=number(node,"arrival-distance",plugin.getConfig().getDouble("behavior.navigation.arrival-distance",1.5));
                speed=(float)number(node,"speed",plugin.getConfig().getDouble("behavior.navigation.speed",1));
                pathfindingRange=(float)number(node,"pathfinding-range",plugin.getConfig().getDouble("behavior.navigation.pathfinding-range",64));
                stuckMillis=(long)(number(node,"stuck-seconds",plugin.getConfig().getDouble("behavior.navigation.stuck-seconds",10))*1000);
                stuckAction=string(node,"stuck-action",plugin.getConfig().getString("behavior.navigation.stuck-action","fail")).toLowerCase(Locale.ROOT);
                stuckRetries=(int)number(node,"stuck-retries",plugin.getConfig().getInt("behavior.navigation.stuck-retries",1));
            }

            void start(){lastNavigation=new NavigationSummary(destination,startedAt,"RUNNING","","pathfinding");if(privateNavigation)projections.markNavigation(player,base,true);task=plugin.getServer().getScheduler().runTaskTimer(plugin,this::poll,1,1);}

            void poll(){
                if(result.isDone())return;
                if(!active()){cancel(false);return;}
                NPC actor=privateNavigation?privateActor():Environment.this.actor();
                if(actor==null||!actor.isSpawned()){
                    if(privateNavigation){String reason=projections.inspect(player,base).reason();if(Set.of("projection limit reached","Citizens rejected projection spawn","presentation world is unavailable","base actor is not Persona-bound").contains(reason)){finish(BehaviorStatus.FAILURE,slug(reason));return;}lastProgress=now();return;}
                    finish(BehaviorStatus.FAILURE,"actor-unavailable");return;
                }
                Location current=actor.getStoredLocation();
                if(current==null||!current.getWorld().equals(target.getWorld())){finish(BehaviorStatus.FAILURE,"actor-world-changed");return;}
                if(privateNavigation)runtime.get().position(ProjectionManager.position(current));
                double distance=current.distance(target);
                if(distance<=arrivalDistance){actor.getNavigator().cancelNavigation();finish(BehaviorStatus.SUCCESS,null);return;}
                if(distance+0.05<bestDistance){bestDistance=distance;lastProgress=now();}
                if(stuckMillis>0&&now()-lastProgress>=stuckMillis){
                    if(stuckAction.equals("teleport")){actor.teleport(target,PlayerTeleportEvent.TeleportCause.PLUGIN);if(privateNavigation)runtime.get().position(ProjectionManager.position(target));finish(BehaviorStatus.SUCCESS,null);return;}
                    if(stuckAction.equals("retry")&&retries++<stuckRetries){actor.getNavigator().cancelNavigation();bestDistance=Double.MAX_VALUE;lastProgress=now();startNavigation(actor);return;}
                    finish(BehaviorStatus.FAILURE,"stuck");return;
                }
                if(!actor.getNavigator().isNavigating())startNavigation(actor);
            }

            private NPC privateActor(){ProjectionManager.Presentation p=projections.inspect(player,base);if(p.position()!=null)runtime.get().position(p.position());return p.projection();}

            private void startNavigation(NPC actor){
                try{
                    var parameters=actor.getNavigator().getLocalParameters();
                    parameters.distanceMargin(arrivalDistance).speedModifier(speed).range(pathfindingRange).stationaryTicks(stuckMillis<=0?-1:Math.max(1,(int)Math.ceil(stuckMillis/50d))).stuckAction(null);
                    if(!actor.getNavigator().canNavigateTo(target,parameters)){finish(BehaviorStatus.FAILURE,"path-not-found");return;}
                    actor.getNavigator().setTarget(target);
                }catch(RuntimeException e){finish(BehaviorStatus.FAILURE,"navigator-rejected-target");}
            }

            void cancel(boolean emitEvent){if(task!=null)task.cancel();NPC actor=privateNavigation?privateActor():Environment.this.actor();if(actor!=null&&actor.isSpawned())actor.getNavigator().cancelNavigation();navigations.remove(operationKey,this);if(privateNavigation)projections.markNavigation(player,base,false);lastNavigation=new NavigationSummary(destination,startedAt,"CANCELLED","FAILURE","cancelled");if(emitEvent)navigationEvent("navigation-cancelled",destination,"cancelled",privateNavigation);result.complete(BehaviorStatus.FAILURE);}

            private void finish(BehaviorStatus status,String reason){if(result.isDone())return;if(task!=null)task.cancel();navigations.remove(operationKey,this);if(privateNavigation){projections.markNavigation(player,base,false);ProjectionManager.Presentation p=projections.inspect(player,base);if(p.position()!=null)runtime.get().position(p.position());}lastNavigation=new NavigationSummary(destination,startedAt,status==BehaviorStatus.SUCCESS?"COMPLETED":"FAILED",status.name(),Objects.toString(reason,""));navigationEvent(status==BehaviorStatus.SUCCESS?"navigation-success":"navigation-failure",destination,reason,privateNavigation);result.complete(status);}
            private String slug(String value){return value.toLowerCase(Locale.ROOT).replace(' ','-');}
        }
    }
    private static boolean compare(NpcMemoryService.Value v,String op,String expected){if(v.type()==NpcMemoryService.Type.NUMBER){double a=v.numberValue(),b=Double.parseDouble(expected);return switch(op){case "greater-than"->a>b;case "greater-than-or-equal"->a>=b;case "less-than"->a<b;case "less-than-or-equal"->a<=b;case "not-equals"->a!=b;default->a==b;};}String actual=String.valueOf(v.value());return op.equals("not-equals")?!actual.equalsIgnoreCase(expected):op.equals("contains")?actual.contains(expected):actual.equalsIgnoreCase(expected);}
    private static String string(BehaviorDefinition.BehaviorNode n,String key,String fallback){Object v=n.options().get(key);return v==null?fallback:String.valueOf(v);}private static boolean bool(BehaviorDefinition.BehaviorNode n,String key,boolean fallback){Object v=n.options().get(key);return v==null?fallback:v instanceof Boolean b?b:Boolean.parseBoolean(String.valueOf(v));}private static double number(BehaviorDefinition.BehaviorNode n,String key,double fallback){Object v=n.options().get(key);return v==null?fallback:v instanceof Number x?x.doubleValue():Double.parseDouble(String.valueOf(v));}
    private static String stateKey(String behaviorId,BehaviorDefinition.BehaviorNode node){return behaviorId+"/"+node.id();}
    private static Duration ttl(BehaviorDefinition.BehaviorNode n){Object raw=n.options().get("ttl");return raw==null?null:Durations.parse(raw);}private static String infer(Object value){if(value instanceof Boolean)return "boolean";if(value instanceof Number)return "number";return "string";}private static CompletionStage<BehaviorStatus> completed(BehaviorStatus s){return CompletableFuture.completedFuture(s);}
}
